import {LineId} from "./line";

/**
 * A train station
 */
export type Station = {
  displayName: string;
  lines: LineId[];
};

/**
 * A list of all {@link Station}s
 */
export const Stations = {
  abbeyRoad: { displayName: "Abbey Road", lines: ["dlr"] },
  abbeyWood: { displayName: "Abbey Wood", lines: ["elizabeth", "thameslink"] },
  actonCentral: { displayName: "Acton Central", lines: ["mildmay"] },
  actonMainLine: { displayName: "Acton Main Line", lines: ["elizabeth"] },
  actonTown: { displayName: "Acton Town", lines: ["district", "piccadilly"] },
  addingtonVillage: { displayName: "Addington Village", lines: ["trams"] },
  addiscombe: { displayName: "Addiscombe", lines: ["trams"] },
  aldgate: { displayName: "Aldgate", lines: ["metropolitan", "circle"] },
  aldgateEast: { displayName: "Aldgate East", lines: ["hammersmithAndCity", "district"] },
  aldrington: { displayName: "Aldrington", lines: ["southern", "thameslink"] },
  alexandraPalace: { displayName: "Alexandra Palace", lines: ["greatNorthern"] },
  allSaints: { displayName: "All Saints", lines: ["dlr"] },
  alperton: { displayName: "Alperton", lines: ["piccadilly"] },
  amersham: { displayName: "Amersham", lines: ["metropolitan"] },
  ampereWay: { displayName: "Ampere Way", lines: ["trams"] },
  anerley: { displayName: "Anerley", lines: ["southern", "windrush"] },
  angel: { displayName: "Angel", lines: ["northern"] },
  archway: { displayName: "Archway", lines: ["northern"] },
  arena: { displayName: "Arena", lines: ["trams"] },
  arlesey: { displayName: "Arlesey", lines: ["greatNorthern", "thameslink"] },
  arndel: { displayName: "Arundel", lines: ["southern"] },
  arnosGrove: { displayName: "Arnos Grove", lines: ["piccadilly"] },
  arsenal: { displayName: "Arsenal", lines: ["piccadilly"] },
  ashfordInternational: { displayName: "Ashford International", lines: ["southern"] },
  ashtead: { displayName: "Ashtead", lines: ["southern"] },
  ashurst: { displayName: "Ashurst", lines: ["southern"] },
  ashwellMorden: { displayName: "Ashwell & Morden", lines: ["greatNorthern", "thameslink"] },
  avenueRoad: { displayName: "Avenue Road", lines: ["trams"] },
  angmering: { displayName: "Angmering", lines: ["southern", "thameslink"] },
  appledore: { displayName: "Appledore", lines: ["southern"] },

  bakerStreet: { displayName: "Baker Street", lines: ["metropolitan", "bakerloo", "circle", "jubilee", "hammersmithAndCity"] },
  balcombe: { displayName: "Balcombe", lines: ["southern", "thameslink"] },
  balham: { displayName: "Balham", lines: ["northern", "southern"] },
  baldock: { displayName: "Baldock", lines: ["greatNorthern", "thameslink"] },
  bank: { displayName: "Bank", lines: ["waterlooAndCity", "northern", "central", "dlr"] },
  banstead: { displayName: "Banstead", lines: ["southern"] },
  barbican: { displayName: "Barbican", lines: ["metropolitan", "circle", "hammersmithAndCity"] },
  barking: { displayName: "Barking", lines: ["district", "hammersmithAndCity", "suffragette"] },
  barkingRiverside: { displayName: "Barking Riverside", lines: ["suffragette"] },
  barkingside: { displayName: "Barkingside", lines: ["central"] },
  barnham: { displayName: "Barnham", lines: ["southern"] },
  baronsCourt: { displayName: "Barons Court", lines: ["district", "piccadilly"] },
  batAndBall: { displayName: "Bat & Ball", lines: ["thameslink"] },
  batterseaPark: { displayName: "Battersea Park", lines: ["windrush", "southern"] },
  batterseaPowerStation: { displayName: "Battersea Power Station", lines: ["northern"] },
  bayswater: { displayName: "Bayswater", lines: ["district", "circle"] },
  bayford: { displayName: "Bayford", lines: ["greatNorthern"] },
  beckenhamHill: { displayName: "Beckenham Hill", lines: ["thameslink"] },
  beckenhamJunction: { displayName: "Beckenham Junction", lines: ["trams", "southern"] },
  beckenhamRoad: { displayName: "Beckenham Road", lines: ["trams"] },
  beckton: { displayName: "Beckton", lines: ["dlr"] },
  becktonPark: { displayName: "Beckton Park", lines: ["dlr"] },
  becontree: { displayName: "Becontree", lines: ["district"] },
  beddington: { displayName: "Beddington", lines: ["trams"] },
  bedford: { displayName: "Bedford", lines: ["thameslink"] },
  bedhampton: { displayName: "Bedhampton", lines: ["southern"] },
  belgraveWalk: { displayName: "Belgrave Walk", lines: ["trams"] },
  belmont: { displayName: "Belmont", lines: ["southern"] },
  belsizePark: { displayName: "Belsize Park", lines: ["northern"] },
  berkhamsted: { displayName: "Berkhamsted", lines: ["southern"] },
  bermondsey: { displayName: "Bermondsey", lines: ["jubilee"] },
  berwick: { displayName: "Berwick", lines: ["southern"] },
  bethnalGreen1: { displayName: "Bethnal Green", lines: ["weaver"] },
  bethnalGreen2: { displayName: "Bethnal Green", lines: ["central"] },
  bexhill: { displayName: "Bexhill", lines: ["southern"] },
  bickley: { displayName: "Bickley", lines: ["thameslink"] },
  biggleswade: { displayName: "Biggleswade", lines: ["greatNorthern", "thameslink"] },
  billingshurst: { displayName: "Billingshurst", lines: ["southern"] },
  birkbeck: { displayName: "Birkbeck", lines: ["trams", "southern"] },
  bishopstone: { displayName: "Bishopstone", lines: ["southern"] },
  bitterne: { displayName: "Bitterne", lines: ["southern"] },
  blackfriars: { displayName: "Blackfriars", lines: ["district", "circle"] },
  blackhorseLane: { displayName: "Blackhorse Lane", lines: ["trams"] },
  blackhorseRoad: { displayName: "Blackhorse Road", lines: ["victoria", "suffragette"] },
  blackwall: { displayName: "Blackwall", lines: ["dlr"] },
  bogNorRegis: { displayName: "Bognor Regis", lines: ["southern"] },
  bondStreet: { displayName: "Bond Street", lines: ["central", "jubilee", "elizabeth"] },
  bookham: { displayName: "Bookham", lines: ["southern"] },
  borough: { displayName: "Borough", lines: ["northern"] },
  bosham: { displayName: "Bosham", lines: ["southern"] },
  bostonManor: { displayName: "Boston Manor", lines: ["piccadilly"] },
  boundsGreen: { displayName: "Bounds Green", lines: ["piccadilly"] },
  bowChurch: { displayName: "Bow Church", lines: ["dlr"] },
  bowRoad: { displayName: "Bow Road", lines: ["district", "hammersmithAndCity"] },
  bowesPark: { displayName: "Bowes Park", lines: ["greatNorthern"] },
  boxHillWesthumble: { displayName: "Box Hill & Westhumble", lines: ["southern"] },
  brentCross: { displayName: "Brent Cross", lines: ["northern"] },
  brentwood: { displayName: "Brentwood", lines: ["elizabeth"] },
  brighton: { displayName: "Brighton", lines: ["southern", "thameslink", "gatwickExpress"] },
  brixton: { displayName: "Brixton", lines: ["victoria"] },
  brockley: { displayName: "Brockley", lines: ["windrush", "southern"] },
  bromleyByBow: { displayName: "Bromley-by-Bow", lines: ["district", "hammersmithAndCity"] },
  bromleySouth: { displayName: "Bromley South", lines: ["thameslink"] },
  brondesbury: { displayName: "Brondesbury", lines: ["mildmay"] },
  brondesburyPark: { displayName: "Brondesbury Park", lines: ["mildmay"] },
  brookmansPark: { displayName: "Brookmans Park", lines: ["greatNorthern"] },
  bruceGrove: { displayName: "Bruce Grove", lines: ["weaver"] },
  buckhurstHill: { displayName: "Buckhurst Hill", lines: ["central"] },
  burgessHill: { displayName: "Burgess Hill", lines: ["southern", "thameslink"] },
  burnham: { displayName: "Burnham", lines: ["elizabeth"] },
  burntOak: { displayName: "Burnt Oak", lines: ["northern"] },
  bushHillPark: { displayName: "Bush Hill Park", lines: ["weaver"] },
  bushey: { displayName: "Bushey", lines: ["lioness"] },
  buxted: { displayName: "Buxted", lines: ["southern"] },

  caledonianRoad: { displayName: "Caledonian Road", lines: ["piccadilly"] },
  caledonianRoadAndBarnsbury: { displayName: "Calendonian Road And Barnsbury", lines: ["mildmay"] },
  cambridge: { displayName: "Cambridge", lines: ["greatNorthern", "thameslink"] },
  cambridgeHeath: { displayName: "Cambridge Heath", lines: ["weaver"] },
  cambridgeNorth: { displayName: "Cambridge North", lines: ["greatNorthern"] },
  camdenRoad: { displayName: "Camden Road", lines: ["mildmay"] },
  camdenTown: { displayName: "Camden Town", lines: ["northern"] },
  canadaWater: { displayName: "Canada Water", lines: ["jubilee", "windrush"] },
  canaryWharf: { displayName: "Canary Wharf", lines: ["jubilee", "elizabeth", "dlr"] },
  canningTown: { displayName: "Canning Town", lines: ["jubilee", "dlr"] },
  cannonStreet: { displayName: "Cannon Street", lines: ["district", "circle"] },
  canonbury: { displayName: "Canonbury", lines: ["mildmay", "windrush"] },
  canonsPark: { displayName: "Canons Park", lines: ["jubilee"] },
  carpendersPark: { displayName: "Carpenders Park", lines: ["lioness"] },
  carshalton: { displayName: "Carshalton", lines: ["southern", "thameslink"] },
  carshaltonBeeches: { displayName: "Carshalton Beeches", lines: ["southern"] },
  caterham: { displayName: "Caterham", lines: ["southern"] },
  catford: { displayName: "Catford", lines: ["thameslink"] },
  centrale: { displayName: "Centrale", lines: ["trams"] },
  chadwellHeath: { displayName: "Chadwell Heath", lines: ["elizabeth"] },
  chalfontAndLatimer: { displayName: "Chalfont & Latimer", lines: ["metropolitan"] },
  chalkFarm: { displayName: "Chalk Farm", lines: ["northern"] },
  chanceryLane: { displayName: "Chancery Lane", lines: ["central"] },
  charingCross: { displayName: "Charing Cross", lines: ["bakerloo", "northern"] },
  charlton: { displayName: "Charlton", lines: ["thameslink"] },
  cheam: { displayName: "Cheam", lines: ["southern"] },
  chesham: { displayName: "Chesham", lines: ["metropolitan"] },
  cheshunt: { displayName: "Cheshunt", lines: ["weaver"] },
  chichester: { displayName: "Chichester", lines: ["southern"] },
  chigwell: { displayName: "Chigwell", lines: ["central"] },
  chingford: { displayName: "Chingford", lines: ["weaver"] },
  chiswickPark: { displayName: "Chiswick Park", lines: ["district"] },
  chorleywood: { displayName: "Chorleywood", lines: ["metropolitan"] },
  churchStreet: { displayName: "Church Street", lines: ["trams"] },
  cityThameslink: { displayName: "City Thameslink", lines: ["thameslink"] },
  claphamCommon: { displayName: "Clapham Common", lines: ["northern"] },
  claphamHighStreet: { displayName: "Clapham High Street", lines: ["windrush"] },
  claphamJunction: { displayName: "Clapham Junction", lines: ["windrush", "mildmay", "southern"] },
  claphamNorth: { displayName: "Clapham North", lines: ["northern"] },
  claphamSouth: { displayName: "Clapham South", lines: ["northern"] },
  clandon: { displayName: "Clandon", lines: ["southern"] },
  clapton: { displayName: "Clapton", lines: ["weaver"] },
  cockfosters: { displayName: "Cockfosters", lines: ["piccadilly"] },
  colindale: { displayName: "Colindale", lines: ["northern"] },
  colliersWood: { displayName: "Colliers Wood", lines: ["northern"] },
  collington: { displayName: "Collington", lines: ["southern"] },
  coombeLane: { displayName: "Coombe Lane", lines: ["trams"] },
  cosham: { displayName: "Cosham", lines: ["southern"] },
  coulsdonSouth: { displayName: "Coulsdon South", lines: ["southern", "thameslink"] },
  coulsdonTown: { displayName: "Coulsdon Town", lines: ["southern"] },
  coventGarden: { displayName: "Covent Garden", lines: ["piccadilly"] },
  crawley: { displayName: "Crawley", lines: ["southern", "thameslink"] },
  crewsHill: { displayName: "Crews Hill", lines: ["greatNorthern"] },
  cricklewood: { displayName: "Cricklewood", lines: ["thameslink"] },
  crossharbour: { displayName: "Crossharbour", lines: ["dlr"] },
  crouchHill: { displayName: "Crouch Hill", lines: ["suffragette"] },
  croxley: { displayName: "Croxley", lines: ["metropolitan"] },
  crystalPalace: { displayName: "Crystal Palace", lines: ["windrush", "southern"] },
  customHouse: { displayName: "Custom House", lines: ["elizabeth", "dlr"] },
  cuttySark: { displayName: "Cutty Sark for Maratime Greenwich", lines: ["dlr"] },
  cyprus: { displayName: "Cyprus", lines: ["dlr"] },

  dagenhamEast: { displayName: "Dagenham East", lines: ["district"] },
  dagenhamHeathway: { displayName: "Dagenham Heathway", lines: ["district"] },
  dalstonJunction: { displayName: "Dalston Junction", lines: ["windrush"] },
  dalstonKingsland: { displayName: "Dalston Kingsland", lines: ["mildmay"] },
  dartford: { displayName: "Dartford", lines: ["thameslink"] },
  debden: { displayName: "Debden", lines: ["central"] },
  denmarkHill: { displayName: "Denmark Hill", lines: ["windrush", "thameslink"] },
  deptford: { displayName: "Deptford", lines: ["thameslink"] },
  deptfordBridge: { displayName: "Deptford Bridge", lines: ["dlr"] },
  devonsRoad: { displayName: "Devons Road", lines: ["dlr"] },
  dollisHill: { displayName: "Dollis Hill", lines: ["jubilee"] },
  dorking: { displayName: "Dorking", lines: ["southern"] },
  draytonPark: { displayName: "Drayton Park", lines: ["greatNorthern"] },
  dundonaldRoad: { displayName: "Dundonald Road", lines: ["trams"] },

  ealingBroadway: { displayName: "Ealing Broadway", lines: ["district", "central", "elizabeth"] },
  ealingCommon: { displayName: "Ealing Common", lines: ["district", "piccadilly"] },
  earlsCourt: { displayName: "Earl's Court", lines: ["district", "piccadilly"] },
  earlswood: { displayName: "Earlswood", lines: ["southern", "thameslink"] },
  eastActon: { displayName: "East Acton", lines: ["central"] },
  eastCroydon: { displayName: "East Croydon", lines: ["trams", "southern", "thameslink"] },
  eastFinchley: { displayName: "East Finchley", lines: ["northern"] },
  eastGrinstead: { displayName: "East Grinstead", lines: ["southern", "thameslink"] },
  eastHam: { displayName: "East Ham", lines: ["district", "hammersmithAndCity"] },
  eastIndia: { displayName: "East India", lines: ["dlr"] },
  eastPutney: { displayName: "East Putney", lines: ["district"] },
  eastcote: { displayName: "Eastcote", lines: ["metropolitan", "piccadilly"] },
  eastleigh: { displayName: "Eastleigh", lines: ["southern"] },
  edgware: { displayName: "Edgware", lines: ["northern"] },
  edgwareRoad1: { displayName: "Edgware Road", lines: ["bakerloo"] },
  edgwareRoad2: { displayName: "Edgware Road", lines: ["hammersmithAndCity", "district", "circle"] },
  edmontonGreen: { displayName: "Edmonton Green", lines: ["weaver"] },
  effinghamJunction: { displayName: "Effingham Junction", lines: ["southern"] },
  elephantAndCastle: { displayName: "Elephant & Castle", lines: ["northern", "bakerloo"] },
  elmPark: { displayName: "Elm Park", lines: ["district"] },
  elmersEnd: { displayName: "Elmers End", lines: ["trams"] },
  elversonRoad: { displayName: "Elverson Road", lines: ["dlr"] },
  embankment: { displayName: "Embankment", lines: ["district", "bakerloo", "northern", "circle"] },
  emersonPark: { displayName: "Emerson Park", lines: ["liberty"] },
  enfieldChase: { displayName: "Enfield Chase", lines: ["greatNorthern"] },
  enfieldTown: { displayName: "Enfield Town", lines: ["weaver"] },
  epping: { displayName: "Epping", lines: ["central"] },
  epsom: { displayName: "Epsom", lines: ["southern"] },
  epsomDowns: { displayName: "Epsom Downs", lines: ["southern"] },
  eridge: { displayName: "Eridge", lines: ["southern"] },
  euston: { displayName: "Euston", lines: ["northern", "victoria", "lioness"] },
  eustonSquare: { displayName: "Euston Square", lines: ["metropolitan", "circle", "hammersmithAndCity"] },
  ely: { displayName: "Ely", lines: ["greatNorthern"] },

  fairlop: { displayName: "Fairlop", lines: ["central"] },
  farringdon: { displayName: "Farringdon", lines: ["metropolitan", "circle", "hammersmithAndCity", "elizabeth", "thameslink"] },
  fieldway: { displayName: "Fieldway", lines: ["trams"] },
  finchleyCentral: { displayName: "Finchley Central", lines: ["northern"] },
  finchleyRoad: { displayName: "Finchley Road", lines: ["metropolitan", "jubilee"] },
  finchleyRoadAndFrognal: { displayName: "Finchley Road & Frognal", lines: ["mildmay"] },
  finsburyPark: { displayName: "Finsbury Park", lines: ["piccadilly", "victoria", "greatNorthern", "thameslink"] },
  forestGate: { displayName: "Forest Gate", lines: ["elizabeth"] },
  forestHill: { displayName: "Forest Hill", lines: ["windrush", "southern"] },
  ford: { displayName: "Ford", lines: ["southern"] },
  foxton: { displayName: "Foxton", lines: ["greatNorthern", "thameslink"] },
  fratton: { displayName: "Fratton", lines: ["southern"] },
  fulhamBroadway: { displayName: "Fulham Broadway", lines: ["district"] },

  gallionsReach: { displayName: "Gallions Reach", lines: ["dlr"] },
  gantsHill: { displayName: "Gants Hill", lines: ["central"] },
  gatwickAirport: { displayName: "Gatwick Airport", lines: ["southern", "thameslink", "gatwickExpress"] },
  georgeStreet: { displayName: "George Street", lines: ["trams"] },
  gideaPark: { displayName: "Gidea Park", lines: ["elizabeth"] },
  gillinghamKent: { displayName: "Gillingham (Kent)", lines: ["thameslink"] },
  gloucesterRoad: { displayName: "Gloucester Road", lines: ["district", "piccadilly", "circle"] },
  godstone: { displayName: "Godstone", lines: ["southern"] },
  goldersGreen: { displayName: "Golders Green", lines: ["northern"] },
  goldhawkRoad: { displayName: "Goldhawk Road", lines: ["hammersmithAndCity", "circle"] },
  goodgeStreet: { displayName: "Goodge Street", lines: ["northern"] },
  goodmayes: { displayName: "Goodmayes", lines: ["elizabeth"] },
  gospelOak: { displayName: "Gospel Oak", lines: ["mildmay", "suffragette"] },
  goringBySea: { displayName: "Goring-by-Sea", lines: ["southern", "thameslink"] },
  grangeHill: { displayName: "Grange Hill", lines: ["central"] },
  gravelHill: { displayName: "Gravel Hill", lines: ["trams"] },
  gravesend: { displayName: "Gravesend", lines: ["thameslink"] },
  greatPortlandStreet: { displayName: "Great Portland Street", lines: ["metropolitan", "circle", "hammersmithAndCity"] },
  greenPark: { displayName: "Green Park", lines: ["piccadilly", "victoria", "jubilee"] },
  greenford: { displayName: "Greenford", lines: ["central"] },
  greenwich: { displayName: "Greenwich", lines: ["dlr", "thameslink"] },
  greenwichPeninsula: { displayName: "IFS Cloud Greenwich Peninsula", lines: ["cableCar"] },
  gunnersbury: { displayName: "Gunnersbury", lines: ["mildmay", "district"] },
  guildford: { displayName: "Guildford", lines: ["southern"] }, 

  hackbridge: { displayName: "Hackbridge", lines: ["southern", "thameslink"] },
  hackneyCentral: { displayName: "Hackney Central", lines: ["mildmay"] },
  hackneyDowns: { displayName: "Hackney Downs", lines: ["weaver"] },
  hackneyWick: { displayName: "Hackney Wick", lines: ["mildmay"] },
  haggerston: { displayName: "Haggerston", lines: ["windrush"] },
  hainault: { displayName: "Hainault", lines: ["central"] },
  hammersmith1: { displayName: "Hammersmith", lines: ["district", "piccadilly"] },
  hammersmith2: { displayName: "Hammersmith", lines: ["hammersmithAndCity", "circle"] },
  hampdenPark: { displayName: "Hampden Park", lines: ["southern"] },
  hampstead: { displayName: "Hampstead", lines: ["northern"] },
  hampsteadHeath: { displayName: "Hampstead Heath", lines: ["mildmay"] },
  hangerLane: { displayName: "Hanger Lane", lines: ["central"] },
  hanwell: { displayName: "Hanwell", lines: ["elizabeth"] },
  harlesden: { displayName: "Harlesden", lines: ["bakerloo", "lioness"] },
  haroldWood: { displayName: "Harold Wood", lines: ["elizabeth"] },
  harpenden: { displayName: "Harpenden", lines: ["thameslink"] },
  harringay: { displayName: "Harringay", lines: ["greatNorthern"] },
  harringayGreenLanes: { displayName: "Harringay Green Lanes", lines: ["suffragette"] },
  harringtonRoad: { displayName: "Harrington Road", lines: ["trams"] },
  harrowAndWealdstone: { displayName: "Harrow & Wealdstone", lines: ["bakerloo", "lioness"] },
  harrowOnTheHill: { displayName: "Harrow-on-the-Hill", lines: ["metropolitan"] },
  hastings: { displayName: "Hastings", lines: ["southern"] },
  hatchEnd: { displayName: "Hatch End", lines: ["lioness"] },
  hattonCross: { displayName: "Hatton Cross", lines: ["piccadilly"] },
  hayesAndHarlington: { displayName: "Hayes & Harlington", lines: ["elizabeth"] },
  haywardsHeath: { displayName: "Haywards Heath", lines: ["southern", "thameslink"] },
  headstoneLane: { displayName: "Headstone Lane", lines: ["lioness"] },
  heathrowTerminalFive: { displayName: "Heathrow Terminal 5", lines: ["piccadilly", "elizabeth"] },
  heathrowTerminalFour: { displayName: "Heathrow Terminal 4", lines: ["piccadilly", "elizabeth"] },
  heathrowTerminalsTwoAndThree: { displayName: "Heathrow Terminals 2 & 3", lines: ["piccadilly", "elizabeth"] },
  hendon: { displayName: "Hendon", lines: ["thameslink"] },
  hendonCentral: { displayName: "Hendon Central", lines: ["northern"] },
  herneHill: { displayName: "Herne Hill", lines: ["thameslink"] },
  heronQuays: { displayName: "Heron Quays", lines: ["dlr"] },
  highBarnet: { displayName: "High Barnet", lines: ["northern"] },
  highStreetKensington: { displayName: "High Street Kensington", lines: ["district", "circle"] },
  highamsPark: { displayName: "Highams Park", lines: ["weaver"] },
  highburyAndIslington: { displayName: "Highbury & Islington", lines: ["victoria", "mildmay", "windrush"] },
  highgate: { displayName: "Highgate", lines: ["northern"] },
  hillingdon: { displayName: "Hillingdon", lines: ["metropolitan", "piccadilly"] },
  hitchin: { displayName: "Hitchin", lines: ["greatNorthern", "thameslink"] },
  holborn: { displayName: "Holborn", lines: ["central", "piccadilly"] },
  hollandPark: { displayName: "Holland Park", lines: ["central"] },
  hollowayRoad: { displayName: "Holloway Road", lines: ["piccadilly"] },
  homerton: { displayName: "Homerton", lines: ["mildmay"] },
  honorOakPark: { displayName: "Honor Oak Park", lines: ["windrush"] },
  hornchurch: { displayName: "Hornchurch", lines: ["district"] },
  hounslowCentral: { displayName: "Hounslow Central", lines: ["piccadilly"] },
  hounslowEast: { displayName: "Hounslow East", lines: ["piccadilly"] },
  hounslowWest: { displayName: "Hounslow West", lines: ["piccadilly"] },
  horsham: { displayName: "Horsham", lines: ["southern", "thameslink"] },
  hove: { displayName: "Hove", lines: ["southern", "thameslink"] },
  hoxton: { displayName: "Hoxton", lines: ["windrush"] },
  hydeParkCorner: { displayName: "Hyde Park Corner", lines: ["piccadilly"] },

  ickenham: {displayName: "Ickenham", lines: ["metropolitan", "piccadilly"]},
  ilford: {displayName: "Ilford", lines: ["elizabeth"]},
  imperialWharf: {displayName: "Imperial Wharf", lines: ["mildmay"]},
  islandGardens: {displayName: "Island Gardens", lines: ["dlr"]},
  iver: {displayName: "Iver", lines: ["elizabeth"]},

  kennington: {displayName: "Kennington", lines: ["northern"]},
  kensalGreen: {displayName: "Kensal Green", lines: ["bakerloo", "lioness"]},
  kensalRise: {displayName: "Kensal Rise", lines: ["mildmay"]},
  kensingtonOlympia: {displayName: "Kensington (Olympia)", lines: ["district", "mildmay"]},
  kentishTown: {displayName: "Kentish Town", lines: ["northern"]},
  kentishTownWest: {displayName: "Kentish Town West", lines: ["mildmay"]},
  kenton: {displayName: "Kenton", lines: ["bakerloo", "lioness"]},
  kewGardens: {displayName: "Kew Gardens", lines: ["district", "mildmay"]},
  kilburn: {displayName: "Kilburn", lines: ["jubilee"]},
  kilburnHighRoad: {displayName: "Kilburn High Road", lines: ["lioness"]},
  kilburnPark: {displayName: "Kilburn Park", lines: ["bakerloo"]},
  kingGeorgeV: {displayName: "King George V", lines: ["dlr"]},
  kingHenrysDrive: {displayName: "King Henry's Drive", lines: ["trams"]},
  kingsCross: { displayName: "Kings Cross", lines: ["greatNorthern", "thameslink"] },
  kingsCrossStPancras: { displayName: "King's Cross St Pancras", lines: ["metropolitan", "northern", "piccadilly", "circle", "victoria", "hammersmithAndCity"]},
  kingsbury: {displayName: "Kingsbury", lines: ["jubilee"]},
  knightsbridge: {displayName: "Knightsbridge", lines: ["piccadilly"]},

  ladbrokeGrove: { displayName: "Ladbroke Grove", lines: ["hammersmithAndCity", "circle"] },
  lambethNorth: { displayName: "Lambeth North", lines: ["bakerloo"] },
  lancasterGate: { displayName: "Lancaster Gate", lines: ["central"] },
  langdonPark: { displayName: "Langdon Park", lines: ["dlr"] },
  langley: { displayName: "Langley", lines: ["elizabeth"] },
  latimerRoad: { displayName: "Latimer Road", lines: ["hammersmithAndCity", "circle"] },
  lebanonRoad: { displayName: "Lebanon Road", lines: ["trams"] },
  leicesterSquare: { displayName: "Leicester Square", lines: ["piccadilly", "northern"] },
  lewisham: { displayName: "Lewisham", lines: ["dlr"] },
  leyton: { displayName: "Leyton", lines: ["central"] },
  leytonMidlandRoad: { displayName: "Leyton Midland Road", lines: ["suffragette"] },
  leytonstone: { displayName: "Leytonstone", lines: ["central"] },
  leytonstoneHighRoad: { displayName: "Leytonstone High Road", lines: ["suffragette"] },
  limehouse: { displayName: "Limehouse", lines: ["dlr"] },
  liverpoolStreet: { displayName: "Liverpool Street", lines: ["metropolitan", "central", "circle", "hammersmithAndCity", "weaver", "elizabeth"],},
  lloydPark: { displayName: "Lloyd Park", lines: ["trams"] },
  londonBridge: { displayName: "London Bridge", lines: ["northern", "jubilee", "southern", "thameslink"] },
  londonCityAirport: { displayName: "London City Airport", lines: ["dlr"] },
  londonFields: { displayName: "London Fields", lines: ["weaver"] },
  londonVictoria: { displayName: "London Victoria", lines: ["southern", "gatwickExpress"] },
  loughton: { displayName: "Loughton", lines: ["central"] },
  luton: { displayName: "Luton", lines: ["thameslink"] },
  lutonAirportParkway: { displayName: "Luton Airport Parkway", lines: ["thameslink"] },

  maidaVale: {displayName: "Maida Vale", lines: ["bakerloo"]},
  maidenhead: {displayName: "maidenhead", lines: ["elizabeth"]},
  manorHouse: {displayName: "Manor House", lines: ["piccadilly"]},
  manorPark: {displayName: "Manor Park", lines: ["elizabeth"]},
  mansionHouse: {displayName: "Mansion House", lines: ["district", "circle"]},
  marbleArch: {displayName: "Marble Arch", lines: ["central"]},
  maryland: {displayName: "Maryland", lines: ["elizabeth"]},
  marylebone: {displayName: "Marylebone", lines: ["bakerloo"]},
  mertonPark: {displayName: "Merton Park", lines: ["trams"]},
  mileEnd: {displayName: "Mile End", lines: ["district", "hammersmithAndCity", "central"]},
  millHillEast: {displayName: "Mill Hill East", lines: ["northern"]},
  mitcham: {displayName: "Mitcham", lines: ["trams"]},
  mitchamJunction: {displayName: "Mitcham Junction", lines: ["trams"]},
  monument: {displayName: "Monument", lines: ["district", "circle"]},
  moorPark: {displayName: "Moor Park", lines: ["metropolitan"]},
  moorgate: {displayName: "Moorgate", lines: ["metropolitan", "northern", "circle", "hammersmithAndCity", "greatNorthern"]},
  morden: {displayName: "Morden", lines: ["northern"]},
  mordenRoad: {displayName: "Morden Road", lines: ["trams"]},
  morningtonCrescent: {displayName: "Mornington Crescent", lines: ["northern"]},
  mudchute: {displayName: "Mudchute", lines: ["dlr"]},

  neasden: {displayName: "Neasden", lines: ["jubilee"]},
  newAddington: {displayName: "New Addington", lines: ["trams"]},
  newCross: {displayName: "New Cross", lines: ["windrush"]},
  newCrossGate: {displayName: "New Cross Gate", lines: ["windrush"]},
  newburyPark: {displayName: "Newbury Park", lines: ["central"]},
  nineElms: {displayName: "Nine Elms", lines: ["northern"]},
  northActon: {displayName: "North Acton", lines: ["central"]},
  northEaling: {displayName: "North Ealing", lines: ["piccadilly"]},
  northHarrow: {displayName: "North Harrow", lines: ["metropolitan"]},
  northWembley: {displayName: "North Wembley", lines: ["bakerloo", "lioness"]},
  northfields: {displayName: "Northfields", lines: ["piccadilly"]},
  northolt: {displayName: "Northolt", lines: ["central"]},
  northwickPark: {displayName: "Northwick Park", lines: ["metropolitan"]},
  northwood: {displayName: "Northwood", lines: ["metropolitan"]},
  northwoodHills: {displayName: "Northwood Hills", lines: ["metropolitan"]},
  norwoodJunction: {displayName: "Norwood Junction", lines: ["windrush", "thameslink", "southern"]},
  nottingHillGate: {displayName: "Notting Hill Gate", lines: ["district", "central", "circle"]},

  oakwood: {displayName: "Oakwood", lines: ["piccadilly"]},
  oldStreet: {displayName: "Old Street", lines: ["northern"]},
  osterley: {displayName: "Osterley", lines: ["piccadilly"]},
  oval: {displayName: "Oval", lines: ["northern"]},
  oxfordCircus: {displayName: "Oxford Circus", lines: ["central", "bakerloo", "victoria"]},
  oxted: { displayName: "Oxted", lines: ["southern", "thameslink"] },


  paddington: { displayName: "Paddington", lines: ["district", "circle", "bakerloo", "hammersmithAndCity", "elizabeth"],},
  parkRoyal: { displayName: "Park Royal", lines: ["piccadilly"] },
  parsonsGreen: { displayName: "Parsons Green", lines: ["district"] },
  peckhamRye: { displayName: "Peckham Rye", lines: ["windrush"] },
  pengeWest: { displayName: "Penge West", lines: ["windrush"] },
  perivale: { displayName: "Perivale", lines: ["central"] },
  phippsBridge: { displayName: "Phipps Bridge", lines: ["trams"] },
  piccadillyCircus: { displayName: "Piccadilly Circus", lines: ["bakerloo", "piccadilly"] },
  pimlico: { displayName: "Pimlico", lines: ["victoria"] },
  pinner: { displayName: "Pinner", lines: ["metropolitan"] },
  plaistow: { displayName: "Plaistow", lines: ["district", "hammersmithAndCity"] },
  pontoonDock: { displayName: "Pontoon Dock", lines: ["dlr"] },
  poplar: { displayName: "Poplar", lines: ["dlr"] },
  portsmouthHarbour: { displayName: "Portsmouth Harbour", lines: ["southern"] },
  portsmouthSouthsea: { displayName: "Portsmouth & Southsea", lines: ["southern"] },
  prestonRoad: { displayName: "Preston Road", lines: ["metropolitan"] },
  princeRegent: { displayName: "Prince Regent", lines: ["dlr"] },
  puddingMillLane: { displayName: "Pudding Mill Lane", lines: ["dlr"] },
  purley: { displayName: "Purley", lines: ["southern", "thameslink"] },

  queensPark: {displayName: "Queen's Park", lines: ["bakerloo", "lioness"]},
  queensRoadPeckham: {displayName: "Queens Road Peckham", lines: ["windrush"]},
  queensbury: {displayName: "Queensbury", lines: ["jubilee"]},
  queensway: {displayName: "Queensway", lines: ["central"]},

  rainhamKent: { displayName: "Rainham (Kent)", lines: ["thameslink"] },
  ravenscourtPark: {displayName: "Ravenscourt Park", lines: ["district"]},
  raynersLane: {displayName: "Rayners Lane", lines: ["metropolitan", "piccadilly"]},
  reading: {displayName: "Reading", lines: ["elizabeth"]},
  rectoryRoad: {displayName: "Rectory Road", lines: ["weaver"]},
  redbridge: {displayName: "Redbridge", lines: ["central"]},
  redhill: { displayName: "Redhill", lines: ["southern", "thameslink"] },
  reevesCorner: {displayName: "Reeves Corner", lines: ["trams"]},
  regentsPark: {displayName: "Regents Park", lines: ["bakerloo"]},
  richmond: {displayName: "Richmond", lines: ["district", "mildmay"]},
  rickmansworth: {displayName: "Rickmansworth", lines: ["metropolitan"]},
  rodingValley: {displayName: "Roding Valley", lines: ["central"]},
  romford: {displayName: "Romford", lines: ["liberty", "elizabeth"]},
  rotherhithe: {displayName: "Rotherhithe", lines: ["windrush"]},
  royalAlbert: {displayName: "Royal Albert", lines: ["dlr"]},
  royalDocks: {displayName: "IFS Cloud Royal Docks", lines: ["cableCar"]},
  royalOak: {displayName: "Royal Oak", lines: ["hammersmithAndCity", "circle"]},
  royalVictoria: {displayName: "Royal Victoria", lines: ["dlr"]},
  ruislip: {displayName: "Ruislip", lines: ["metropolitan", "piccadilly"]},
  ruislipGardens: {displayName: "Ruislip Gardens", lines: ["central"]},
  ruislipManor: {displayName: "Ruislip Manor", lines: ["metropolitan", "piccadilly"]},
  russellSquare: {displayName: "Russell Square", lines: ["piccadilly"]},

  sandilands: { displayName: "Sandilands", lines: ["trams"] },
  sevenKings: { displayName: "Seven Kings", lines: ["elizabeth"] },
  sevenSisters: { displayName: "Seven Sisters", lines: ["victoria", "weaver"] },
  shadwell: { displayName: "Shadwell", lines: ["windrush", "dlr"] },
  shenfield: { displayName: "Shenfield", lines: ["elizabeth"] },
  shepherdsBush: { displayName: "Shepherd's Bush", lines: ["central", "mildmay"] },
  shepherdsBushMarket: { displayName: "Shepherd's Bush Market", lines: ["hammersmithAndCity", "circle"] },
  shoreditchHighStreet: { displayName: "Shoreditch High Street", lines: ["windrush"] },
  silverStreet: { displayName: "Silver Street", lines: ["weaver"] },
  sloaneSquare: { displayName: "Sloane Square", lines: ["district", "circle"] },
  slough: { displayName: "Slough", lines: ["elizabeth"] },
  snaresbrook: { displayName: "Snaresbrook", lines: ["central"] },
  southActon: { displayName: "South Acton", lines: ["mildmay"] },
  southEaling: { displayName: "South Ealing", lines: ["piccadilly"] },
  southHampstead: { displayName: "South Hampstead", lines: ["lioness"] },
  southHarrow: { displayName: "South Harrow", lines: ["piccadilly"] },
  southKensington: { displayName: "South Kensington", lines: ["district", "circle", "piccadilly"] },
  southKenton: { displayName: "South Kenton", lines: ["bakerloo", "lioness"] },
  southQuay: { displayName: "South Quay", lines: ["dlr"] },
  southRuislip: { displayName: "South Ruislip", lines: ["central"] },
  southTottenham: { displayName: "South Tottenham", lines: ["suffragette"] },
  southWimbledon: { displayName: "South Wimbledon", lines: ["northern"] },
  southWoodford: { displayName: "South Woodford", lines: ["central"] },
  southall: { displayName: "Southall", lines: ["elizabeth"] },
  southbury: { displayName: "Southbury", lines: ["weaver"] },
  southfields: { displayName: "Southfields", lines: ["district"] },
  southgate: { displayName: "Southgate", lines: ["piccadilly"] },
  southwark: { displayName: "Southwark", lines: ["jubilee"] },
  stJamesPark: { displayName: "St James's Park", lines: ["district", "circle"] },
  stJamesStreet: { displayName: "St James Street", lines: ["weaver"] },
  stJohnsWood: { displayName: "St John's Wood", lines: ["jubilee"] },
  stPauls: { displayName: "St Paul's", lines: ["central"] },
  stamfordBrook: { displayName: "Stamford Brook", lines: ["district"] },
  stamfordHill: { displayName: "Stamford Hill", lines: ["weaver"] },
  stanmore: { displayName: "Stanmore", lines: ["jubilee"] },
  starLane: { displayName: "Star Lane", lines: ["dlr"] },
  stepneyGreen: { displayName: "Stepney Green", lines: ["district", "hammersmithAndCity"] },
  stockwell: { displayName: "Stockwell", lines: ["victoria", "northern"] },
  stokeNewington: { displayName: "Stoke Newington", lines: ["weaver"] },
  stonebridgePark: { displayName: "Stonebridge Park", lines: ["bakerloo", "lioness"] },
  stratford: { displayName: "Stratford", lines: ["central", "jubilee", "mildmay", "elizabeth", "dlr"] },
  stratfordHighStreet: { displayName: "Stratford High Street", lines: ["dlr"] },
  stratfordInternational: { displayName: "Stratford International", lines: ["dlr"] },
  streatham: { displayName: "Streatham", lines: ["southern", "thameslink"] },
  sudburyHill: { displayName: "Sudbury Hill", lines: ["piccadilly"] },
  sudburyTown: { displayName: "Sudbury Town", lines: ["piccadilly"] },
  surreyQuays: { displayName: "Surrey Quays", lines: ["windrush"] },
  sutton: { displayName: "Sutton", lines: ["southern", "thameslink"] },
  swissCottage: { displayName: "Swiss Cottage", lines: ["jubilee"] },
  sydenham: { displayName: "Sydenham", lines: ["windrush"] },

  taplow: {displayName: "Taplow", lines: ["elizabeth"]},
  temple: {displayName: "Temple", lines: ["district", "circle"]},
  theobaldsGrove: {displayName: "Theobalds Grove", lines: ["weaver"]},
  therapiaLane: {displayName: "Therapia Lane", lines: ["trams"]},
  theydonBois: {displayName: "Theydon Bois", lines: ["central"]},
  tootingBec: {displayName: "Tooting Bec", lines: ["northern"]},
  tootingBroadway: {displayName: "Tooting Broadway", lines: ["northern"]},
  tottenhamCourtRoad: {displayName: "Tottenham Court Road", lines: ["northern", "central", "elizabeth"]},
  tottenhamHale: {displayName: "Tottenham Hale", lines: ["victoria"]},
  totteridgeAndWhetstone: {displayName: "Totteridge & Whetstone", lines: ["northern"]},
  towerGateway: {displayName: "Tower Gateway", lines: ["dlr"]},
  towerHill: {displayName: "Tower Hill", lines: ["district", "circle"]},
  tufnellPark: {displayName: "Tufnell Park", lines: ["northern"]},
  turkeyStreet: {displayName: "Turkey Street", lines: ["weaver"]},
  turnhamGreen: {displayName: "Turnham Green", lines: ["district", "piccadilly"]},
  turnpikeLane: {displayName: "Turnpike Lane", lines: ["piccadilly"]},
  twyford: {displayName: "Twyford", lines: ["elizabeth"]},

  upminster: {displayName: "Upminster", lines: ["district", "liberty"]},
  upminsterBridge: {displayName: "Upminster Bridge", lines: ["district"]},
  upney: {displayName: "Upney", lines: ["district"]},
  upperHolloway: {displayName: "Upper Holloway", lines: ["suffragette"]},
  uptonPark: {displayName: "Upton Park", lines: ["district"]},
  uxbridge: {displayName: "Uxbridge", lines: ["metropolitan", "piccadilly"]},

  vauxhall: {displayName: "Vauxhall", lines: ["victoria"]},
  victoria: {displayName: "Victoria", lines: ["victoria", "district", "circle"]},

  waddonMarsh: {displayName: "Waddon Marsh", lines: ["trams"]},
  walthamstowCentral: {displayName: "Walthamstow Central", lines: ["victoria", "weaver"]},
  walthamstowQueensRoad: {displayName: "Walthamstow Queen's Road", lines: ["suffragette"]},
  wandlePark: {displayName: "Wandle Park", lines: ["trams"]},
  wandsworthRoad: {displayName: "Wandsworth Road", lines: ["windrush"]},
  wanstead: {displayName: "Wanstead", lines: ["central"]},
  wansteadPark: {displayName: "Wanstead Park", lines: ["suffragette"]},
  wapping: {displayName: "Wapping", lines: ["windrush"]},
  warrenStreet: {displayName: "Warren Street", lines: ["northern", "victoria"]},
  warwickAvenue: {displayName: "Warwick Avenue", lines: ["bakerloo"]},
  waterloo: {displayName: "Waterloo", lines: ["waterlooAndCity", "bakerloo", "northern", "jubilee"]},
  watford: {displayName: "Watford", lines: ["metropolitan"]},
  watfordHighStreet: {displayName: "Watford High Street", lines: ["lioness"]},
  watfordJunction: {displayName: "Watford Junction", lines: ["lioness"]},
  wellesleyRoad: {displayName: "Wellesley Road", lines: ["trams"]},
  wembleyCentral: {displayName: "Wembley Central", lines: ["bakerloo", "lioness"]},
  wembleyPark: {displayName: "Wembley Park", lines: ["metropolitan", "jubilee"]},
  westActon: {displayName: "West Acton", lines: ["central"]},
  westCroydon: {displayName: "West Croydon", lines: ["windrush", "trams"]},
  westDrayton: {displayName: "West Drayton", lines: ["elizabeth"]},
  westEaling: {displayName: "West Ealing", lines: ["elizabeth"]},
  westFichley: {displayName: "West Finchley", lines: ["northern"]},
  westHam: {displayName: "West Ham", lines: ["district", "hammersmithAndCity", "jubilee", "dlr"]},
  westHampstead: {displayName: "West Hampstead", lines: ["jubilee", "mildmay"]},
  westHarrow: {displayName: "West Harrow", lines: ["metropolitan"]},
  westIndiaQuay: {displayName: "West India Quay", lines: ["dlr"]},
  westKensington: {displayName: "West Kensington", lines: ["district"]},
  westRuislip: {displayName: "West Ruislip", lines: ["central"]},
  westSilvertown: {displayName: "West Silvertown", lines: ["dlr"]},
  westbournePark: {displayName: "Westbourne Park", lines: ["hammersmithAndCity", "circle"]},
  westbrompton: {displayName: "West Brompton", lines: ["district", "mildmay"]},
  westferry: {displayName: "Westferry", lines: ["dlr"]},
  westminster: {displayName: "Westminster", lines: ["district", "circle", "jubilee"]},
  whiteCity: {displayName: "White City", lines: ["central"]},
  whiteHartLane: {displayName: "White Hart Lane", lines: ["weaver"]},
  whitechapel: {displayName: "Whitechapel", lines: ["district", "hammersmithAndCity", "windrush", "elizabeth"]},
  willesdenGreen: {displayName: "Willesden Green", lines: ["jubilee"]},
  willesdenJunction: {displayName: "Willesden Junction", lines: ["bakerloo", "lioness", "mildmay"]},
  wimbledon: {displayName: "Wimbledon", lines: ["district", "trams", "thameslink"]},
  wimbledonPark: {displayName: "Wimbledon Park", lines: ["district"]},
  woodGreen: {displayName: "Wood Green", lines: ["piccadilly"]},
  woodStreet: {displayName: "Wood Street", lines: ["weaver"]},
  woodford: {displayName: "Woodford", lines: ["central"]},
  woodgrangePark: {displayName: "Woodgrange Park", lines: ["suffragette"]},
  woodside: {displayName: "Woodside", lines: ["trams"]},
  woodsidePark: {displayName: "Woodside Park", lines: ["northern"]},
  woolwich: {displayName: "Woolwich", lines: ["elizabeth"]},
  woolwichArsenal: {displayName: "Woolwich Arsenal", lines: ["dlr"]},

} as const satisfies Record<string, Station>;

export type StationId = keyof typeof Stations;
export const stationIds = Object.keys(Stations) as StationId[];
