import {LineId} from "./line";

/**
 * A train station
 */
export type Station = {
  displayName: string;
  lines: LineId[];
};

/**
 * A list of all {@link Station}s
 */
export const Stations = {
  abbeyRoad: {displayName: "Abbey Road", lines: ["dlr"]},
  abbeyWood: {displayName: "Abbey Wood", lines: ["elizabeth", "thameslink"]},
  actonCentral: {displayName: "Acton Central", lines: ["mildmay"]},
  actonMainLine: {displayName: "Acton Main Line", lines: ["elizabeth"]},
  actonTown: {displayName: "Acton Town", lines: ["district", "piccadilly"]},
  addingtonVillage: {displayName: "Addington Village", lines: ["trams"]},
  addiscombe: {displayName: "Addiscombe", lines: ["trams"]},
  aldgate: {displayName: "Aldgate", lines: ["metropolitan", "circle"]},
  aldgateEast: {displayName: "Aldgate East", lines: ["hammersmithAndCity", "district"]},
  aldrington: {displayName: "Aldrington", lines: ["thameslink"]},
  alexandraPalace: {displayName: "Alexandra Palace", lines: ["thameslink"]},
  allSaints: {displayName: "All Saints", lines: ["dlr"]},
  alperton: {displayName: "Alperton", lines: ["piccadilly"]},
  amberley: {displayName: "Amberley", lines: ["thameslink"]},
  amersham: {displayName: "Amersham", lines: ["metropolitan"]},
  ampereWay: {displayName: "Ampere Way", lines: ["trams"]},
  anerley: {displayName: "Anerly", lines: ["windrush", "thameslink"]},
  angel: {displayName: "Angel", lines: ["northern"]},
  angmering: {displayName: "Angering", lines: ["thameslink"]},
  appledoreKent: {displayName: "Appledore (Kent)", lines: ["thameslink"]},
  archway: {displayName: "Archway", lines: ["northern"]},
  arena: {displayName: "Arena", lines: ["trams"]},
  arlesey: {displayName: "Arlesey", lines: ["thameslink"]},
  arnosGrove: {displayName: "Arnos Grove", lines: ["piccadilly"]},
  arsenal: {displayName: "Arsenal", lines: ["piccadilly"]},
  arundel: {displayName: "Arundel", lines: ["thameslink"]},
  ashfordInternational: {displayName: "Ashford International", lines: ["thameslink"]},
  ashtead: {displayName: "Ashtead", lines: ["thameslink"]},
  ashurstKent: {displayName: "Ashurst (Kent)", lines: ["thameslink"]},
  ashwellAndMorden: {displayName: "Ashwell & Morden", lines: ["thameslink"]},
  avenueRoad: {displayName: "Avenue Road", lines: ["trams"]},
  bakerStreet: {displayName: "Baker Street", lines: ["metropolitan", "bakerloo", "circle", "jubilee", "hammersmithAndCity"]},
  balcombe: {displayName: "Balcombe", lines: ["thameslink"]},
  baldock: {displayName: "Baldock", lines: ["thameslink"]},
  balham: {displayName: "Balham", lines: ["northern", "thameslink"]},
  bank: {displayName: "Bank", lines: ["waterlooAndCity", "northern", "central", "dlr"]},
  banstead: {displayName: "Banstead", lines: ["thameslink"]},
  barbican: {displayName: "Barbican", lines: ["metropolitan", "circle", "hammersmithAndCity"]},
  barking: {displayName: "Barking", lines: ["district", "hammersmithAndCity", "suffragette"]},
  barkingRiverside: {displayName: "Barking Riverside", lines: ["suffragette"]},
  barkingside: {displayName: "Barkingside", lines: ["central"]},
  barnham: {displayName: "Barnham", lines: ["thameslink"]},
  baronsCourt: {displayName: "Barons Court", lines: ["district", "piccadilly"]},
  batAndBall: {displayName: "Bat & Ball", lines: ["thameslink"]},
  batterseaPark: {displayName: "Battersea Park", lines: ["windrush", "thameslink"]},
  batterseaPowerStation: {displayName: "Battersea Power Station", lines: ["northern"]},
  bayford: {displayName: "Bayford", lines: ["thameslink"]},
  bayswater: {displayName: "Bayswater", lines: ["district", "circle"]},
  beckenhamHill: {displayName: "Beckenham Hill", lines: ["thameslink"]},
  beckenhamJunction: {displayName: "Beckenham Junction", lines: ["trams", "thameslink"]},
  beckenhamRoad: {displayName: "Beckenham Road", lines: ["trams"]},
  beckton: {displayName: "Beckton", lines: ["dlr"]},
  becktonPark: {displayName: "Beckton Park", lines: ["dlr"]},
  becontree: {displayName: "Becontree", lines: ["district"]},
  beddington: {displayName: "Beddington", lines: ["trams"]},
  bedford: {displayName: "Bedford", lines: ["thameslink"]},
  bedhampton: {displayName: "Bedhampton", lines: ["thameslink"]},
  belgraveWalk: {displayName: "Belgrave Walk", lines: ["trams"]},
  bellingham: {displayName: "Bellingham", lines: ["thameslink"]},
  belmont: {displayName: "Belmont", lines: ["thameslink"]},
  belsizePark: {displayName: "Belsize Park", lines: ["northern"]},
  berkhamsted: {displayName: "Berkhamsted", lines: ["thameslink"]},
  bermondsey: {displayName: "Bermondsey", lines: ["jubilee"]},
  berwickSussex: {displayName: "Berwick (Sussex)", lines: ["thameslink"]},
  bethnalGreen1: {displayName: "Bethnal Green", lines: ["weaver"]},
  bethnalGreen2: {displayName: "Bethnal Green", lines: ["central"]},
  bexhill: {displayName: "Bexhill", lines: ["thameslink"]},
  bickley: {displayName: "Bickley", lines: ["thameslink"]},
  biggleswade: {displayName: "Biggleswade", lines: ["thameslink"]},
  billingshurst: {displayName: "Billingshurst", lines: ["thameslink"]},
  birkbeck: {displayName: "Birkbeck", lines: ["trams", "thameslink"]},
  bishopstoneSussex: {displayName: "Bishopstone (Sussex)", lines: ["thameslink"]},
  bitterne: {displayName: "Bitterne", lines: ["thameslink"]},
  blackfriars: {displayName: "Blackfriars", lines: ["district", "circle"]},
  blackhorseLane: {displayName: "Blackhorse Lane", lines: ["trams"]},
  blackhorseRoad: {displayName: "Blackhorse Road", lines: ["victoria", "suffragette"]},
  blackwall: {displayName: "Blackwall", lines: ["dlr"]},
  bletchley: {displayName: "Bletchley", lines: ["thameslink"]},
  bognorRegis: {displayName: "Bognor Regis", lines: ["thameslink"]},
  bondStreet: {displayName: "Bond Street", lines: ["central", "jubilee", "elizabeth"]},
  bookham: {displayName: "Bookham", lines: ["thameslink"]},
  borough: {displayName: "Borough", lines: ["northern"]},
  bosham: {displayName: "Bosham", lines: ["thameslink"]},
  bostonManor: {displayName: "Boston Manor", lines: ["piccadilly"]},
  boundsGreen: {displayName: "Bounds Green", lines: ["piccadilly"]},
  bowChurch: {displayName: "Bow Church", lines: ["dlr"]},
  bowRoad: {displayName: "Bow Road", lines: ["district", "hammersmithAndCity"]},
  bowesPark: {displayName: "Bowes Park", lines: ["thameslink"]},
  boxHillAndWesthumble: {displayName: "Box Hill & Westhumble", lines: ["thameslink"]},
  brentCross: {displayName: "Brent Cross", lines: ["northern"]},
  brentCrossWest: {displayName: "Brent Cross West", lines: ["thameslink"]},
  brentwood: {displayName: "Brentwood", lines: ["elizabeth"]},
  brightonEastSussex: {displayName: "Brighton (East Sussex)", lines: ["thameslink"]},
  brixton: {displayName: "Brixton", lines: ["victoria"]},
  brockley: {displayName: "Brockley", lines: ["windrush", "thameslink"]},
  bromleyByBow: {displayName: "Bromley-by-Bow", lines: ["district", "hammersmithAndCity"]},
  bromleySouth: {displayName: "Bromley South", lines: ["thameslink"]},
  brondesbury: {displayName: "Brondesbury", lines: ["mildmay"]},
  brondesburyPark: {displayName: "Brondesbury Park", lines: ["mildmay"]},
  brookmansPark: {displayName: "Brookmans Park", lines: ["thameslink"]},
  bruceGrove: {displayName: "Bruce Grove", lines: ["weaver"]},
  buckhurstHill: {displayName: "Buckhurst Hill", lines: ["central"]},
  burgessHill: {displayName: "Burgess Hill", lines: ["thameslink"]},
  burnham: {displayName: "Burnham", lines: ["elizabeth"]},
  burntOak: {displayName: "Burnt Oak", lines: ["northern"]},
  bursledon: {displayName: "Bursledon", lines: ["thameslink"]},
  bushHillPark: {displayName: "Bush Hill Park", lines: ["weaver"]},
  bushey: {displayName: "Bushey", lines: ["lioness"]},
  buxted: {displayName: "Buxted", lines: ["thameslink"]},
  caledonianRoad: {displayName: "Caledonian Road", lines: ["piccadilly"]},
  caledonianRoadAndBarnsbury: {displayName: "Calendonian Road And Barnsbury", lines: ["mildmay"]},
  cambridge: {displayName: "Cambridge", lines: ["thameslink"]},
  cambridgeHeath: {displayName: "Cambridge Heath", lines: ["weaver"]},
  cambridgeNorth: {displayName: "Cambridge North", lines: ["thameslink"]},
  camdenRoad: {displayName: "Camden Road", lines: ["mildmay"]},
  camdenTown: {displayName: "Camden Town", lines: ["northern"]},
  canadaWater: {displayName: "Canada Water", lines: ["jubilee", "windrush"]},
  canaryWharf: {displayName: "Canary Wharf", lines: ["jubilee", "elizabeth", "dlr"]},
  canningTown: {displayName: "Canning Town", lines: ["jubilee", "dlr"]},
  cannonStreet: {displayName: "Cannon Street", lines: ["district", "circle"]},
  canonbury: {displayName: "Canonbury", lines: ["mildmay", "windrush"]},
  canonsPark: {displayName: "Canons Park", lines: ["jubilee"]},
  carpendersPark: {displayName: "Carpenders Park", lines: ["lioness"]},
  carshalton: {displayName: "Carshalton", lines: ["thameslink"]},
  carshaltonBeeches: {displayName: "Carshalton Beeches", lines: ["thameslink"]},
  caterham: {displayName: "Caterham", lines: ["thameslink"]},
  catford: {displayName: "Catford", lines: ["thameslink"]},
  centrale: {displayName: "Centrale", lines: ["trams"]},
  chadwellHeath: {displayName: "Chadwell Heath", lines: ["elizabeth"]},
  chalfontAndLatimer: {displayName: "Chalfont & Latimer", lines: ["metropolitan"]},
  chalkFarm: {displayName: "Chalk Farm", lines: ["northern"]},
  chanceryLane: {displayName: "Chancery Lane", lines: ["central"]},
  charingCross: {displayName: "Charing Cross", lines: ["bakerloo", "northern"]},
  charlton: {displayName: "Charlton", lines: ["thameslink"]},
  chatham: {displayName: "Chatham", lines: ["thameslink"]},
  cheam: {displayName: "Cheam", lines: ["thameslink"]},
  chesham: {displayName: "Chesham", lines: ["metropolitan"]},
  cheshunt: {displayName: "Cheshunt", lines: ["weaver"]},
  chichester: {displayName: "Chichester", lines: ["thameslink"]},
  chigwell: {displayName: "Chigwell", lines: ["central"]},
  chingford: {displayName: "Chingford", lines: ["weaver"]},
  chipstead: {displayName: "Chipstead", lines: ["thameslink"]},
  chiswickPark: {displayName: "Chiswick Park", lines: ["district"]},
  chorleywood: {displayName: "Chorleywood", lines: ["metropolitan"]},
  christsHospital: {displayName: "Christs Hospital", lines: ["thameslink"]},
  churchStreet: {displayName: "Church Street", lines: ["trams"]},
  cityThameslink: {displayName: "City Thameslink", lines: ["thameslink"]},
  clandon: {displayName: "Clandon", lines: ["thameslink"]},
  claphamCommon: {displayName: "Clapham Common", lines: ["northern"]},
  claphamHighStreet: {displayName: "Clapham High Street", lines: ["windrush"]},
  claphamJunction: {displayName: "Clapham Junction", lines: ["windrush", "mildmay", "thameslink"]},
  claphamNorth: {displayName: "Clapham North", lines: ["northern"]},
  claphamSouth: {displayName: "Clapham South", lines: ["northern"]},
  clapton: {displayName: "Clapton", lines: ["weaver"]},
  cockfosters: {displayName: "Cockfosters", lines: ["piccadilly"]},
  colindale: {displayName: "Colindale", lines: ["northern"]},
  colliersWood: {displayName: "Colliers Wood", lines: ["northern"]},
  collington: {displayName: "Collington", lines: ["thameslink"]},
  coodenBeach: {displayName: "Cooden Beach", lines: ["thameslink"]},
  cooksbridge: {displayName: "Cooksbridge", lines: ["thameslink"]},
  coombeLane: {displayName: "Coombe Lane", lines: ["trams"]},
  cosham: {displayName: "Cosham", lines: ["thameslink"]},
  coulsdonSouth: {displayName: "Coulsdon South", lines: ["thameslink"]},
  coulsdonTown: {displayName: "Coulsdon Town", lines: ["thameslink"]},
  coventGarden: {displayName: "Covent Garden", lines: ["piccadilly"]},
  cowdenKent: {displayName: "Cowden (Kent)", lines: ["thameslink"]},
  crawley: {displayName: "Crawley", lines: ["thameslink"]},
  crewsHill: {displayName: "Crews Hill", lines: ["thameslink"]},
  cricklewood: {displayName: "Cricklewood", lines: ["thameslink"]},
  croftonPark: {displayName: "Crofton Park", lines: ["thameslink"]},
  crossharbour: {displayName: "Crossharbour", lines: ["dlr"]},
  crouchHill: {displayName: "Crouch Hill", lines: ["suffragette"]},
  crowborough: {displayName: "Crowborough", lines: ["thameslink"]},
  croxley: {displayName: "Croxley", lines: ["metropolitan"]},
  crystalPalace: {displayName: "Crystal Palace", lines: ["windrush", "thameslink"]},
  cuffley: {displayName: "Cuffley", lines: ["thameslink"]},
  customHouse: {displayName: "Custom House", lines: ["elizabeth", "dlr"]},
  cuttySark: {displayName: "Cutty Sark for Maratime Greenwich", lines: ["dlr"]},
  cyprus: {displayName: "Cyprus", lines: ["dlr"]},
  dagenhamEast: {displayName: "Dagenham East", lines: ["district"]},
  dagenhamHeathway: {displayName: "Dagenham Heathway", lines: ["district"]},
  dalstonJunction: {displayName: "Dalston Junction", lines: ["windrush"]},
  dalstonKingsland: {displayName: "Dalston Kingsland", lines: ["mildmay"]},
  dartford: {displayName: "Dartford", lines: ["thameslink"]},
  debden: {displayName: "Debden", lines: ["central"]},
  denmarkHill: {displayName: "Denmark Hill", lines: ["windrush", "thameslink"]},
  deptford: {displayName: "Deptford", lines: ["thameslink"]},
  deptfordBridge: {displayName: "Deptford Bridge", lines: ["dlr"]},
  devonsRoad: {displayName: "Devons Road", lines: ["dlr"]},
  doleham: {displayName: "Doleham", lines: ["thameslink"]},
  dollisHill: {displayName: "Dollis Hill", lines: ["jubilee"]},
  dorkingMain: {displayName: "Dorking (Main)", lines: ["thameslink"]},
  dormans: {displayName: "Dormans", lines: ["thameslink"]},
  downhamMarket: {displayName: "Downham Market", lines: ["thameslink"]},
  draytonPark: {displayName: "Drayton Park", lines: ["thameslink"]},
  dundonaldRoad: {displayName: "Dundonald Road", lines: ["trams"]},
  durringtonOnSea: {displayName: "Durrington-on-Sea", lines: ["thameslink"]},
  ealingBroadway: {displayName: "Ealing Broadway", lines: ["district", "central", "elizabeth"]},
  ealingCommon: {displayName: "Ealing Common", lines: ["district", "piccadilly"]},
  earlsCourt: {displayName: "Earl's Court", lines: ["district", "piccadilly"]},
  earlswoodSurrey: {displayName: "Earlswood (Surrey)", lines: ["thameslink"]},
  eastActon: {displayName: "East Acton", lines: ["central"]},
  eastCroydon: {displayName: "East Croydon", lines: ["trams", "thameslink"]},
  eastDulwich: {displayName: "East Dulwich", lines: ["thameslink"]},
  eastFinchley: {displayName: "East Finchley", lines: ["northern"]},
  eastGrinstead: {displayName: "East Grinstead", lines: ["thameslink"]},
  eastHam: {displayName: "East Ham", lines: ["district", "hammersmithAndCity"]},
  eastIndia: {displayName: "East India", lines: ["dlr"]},
  eastPutney: {displayName: "East Putney", lines: ["district"]},
  eastWorthing: {displayName: "East Worthing", lines: ["thameslink"]},
  eastbourne: {displayName: "Eastbourne", lines: ["thameslink"]},
  eastcote: {displayName: "Eastcote", lines: ["metropolitan", "piccadilly"]},
  eastleigh: {displayName: "Eastleigh", lines: ["thameslink"]},
  edenbridge: {displayName: "Edenbridge", lines: ["thameslink"]},
  edenbridgeTown: {displayName: "Edenbridge Town", lines: ["thameslink"]},
  edgware: {displayName: "Edgware", lines: ["northern"]},
  edgwareRoad1: {displayName: "Edgware Road", lines: ["bakerloo"]},
  edgwareRoad2: {displayName: "Edgware Road", lines: ["hammersmithAndCity", "district", "circle"]},
  edmontonGreen: {displayName: "Edmonton Green", lines: ["weaver"]},
  effinghamJunction: {displayName: "Effingham Junction", lines: ["thameslink"]},
  elephantAndCastle: {displayName: "Elephant & Castle", lines: ["northern", "bakerloo", "thameslink"]},
  elmPark: {displayName: "Elm Park", lines: ["district"]},
  elmersEnd: {displayName: "Elmers End", lines: ["trams"]},
  elstreeAndBorehamwood: {displayName: "Elstree & Borehamwood", lines: ["thameslink"]},
  elversonRoad: {displayName: "Elverson Road", lines: ["dlr"]},
  ely: {displayName: "Ely", lines: ["thameslink"]},
  embankment: {displayName: "Embankment", lines: ["district", "bakerloo", "northern", "circle"]},
  emersonPark: {displayName: "Emerson Park", lines: ["liberty"]},
  emsworth: {displayName: "Emsworth", lines: ["thameslink"]},
  enfieldChase: {displayName: "Enfield Chase", lines: ["thameslink"]},
  enfieldTown: {displayName: "Enfield Town", lines: ["weaver"]},
  epping: {displayName: "Epping", lines: ["central"]},
  epsomDowns: {displayName: "Epsom Downs", lines: ["thameslink"]},
  epsomSurrey: {displayName: "Epsom (Surrey)", lines: ["thameslink"]},
  eridge: {displayName: "Eridge", lines: ["thameslink"]},
  essexRoad: {displayName: "Essex Road", lines: ["thameslink"]},
  euston: {displayName: "Euston", lines: ["northern", "victoria", "lioness"]},
  eustonSquare: {displayName: "Euston Square", lines: ["metropolitan", "circle", "hammersmithAndCity"]},
  ewellEast: {displayName: "Ewell East", lines: ["thameslink"]},
  eynsford: {displayName: "Eynsford", lines: ["thameslink"]},
  fairlop: {displayName: "Fairlop", lines: ["central"]},
  falmer: {displayName: "Falmer", lines: ["thameslink"]},
  fareham: {displayName: "Fareham", lines: ["thameslink"]},
  farringdon: {displayName: "Farringdon", lines: ["metropolitan", "circle", "hammersmithAndCity", "elizabeth", "thameslink"]},
  faygate: {displayName: "Faygate", lines: ["thameslink"]},
  fieldway: {displayName: "Fieldway", lines: ["trams"]},
  finchleyCentral: {displayName: "Finchley Central", lines: ["northern"]},
  finchleyRoad: {displayName: "Finchley Road", lines: ["metropolitan", "jubilee"]},
  finchleyRoadAndFrognal: {displayName: "Finchley Road & Frognal", lines: ["mildmay"]},
  finsburyPark: {displayName: "Finsbury Park", lines: ["piccadilly", "victoria", "thameslink"]},
  fishbourneSussex: {displayName: "Fishbourne (Sussex)", lines: ["thameslink"]},
  fishersgate: {displayName: "Fishersgate", lines: ["thameslink"]},
  flitwick: {displayName: "Flitwick", lines: ["thameslink"]},
  ford: {displayName: "Ford", lines: ["thameslink"]},
  forestGate: {displayName: "Forest Gate", lines: ["elizabeth"]},
  forestHill: {displayName: "Forest Hill", lines: ["windrush", "thameslink"]},
  foxton: {displayName: "Foxton", lines: ["thameslink"]},
  fratton: {displayName: "Fratton", lines: ["thameslink"]},
  fulhamBroadway: {displayName: "Fulham Broadway", lines: ["district"]},
  gallionsReach: {displayName: "Gallions Reach", lines: ["dlr"]},
  gantsHill: {displayName: "Gants Hill", lines: ["central"]},
  gatwickAirport: {displayName: "Gatwick Airport", lines: ["thameslink"]},
  georgeStreet: {displayName: "George Street", lines: ["trams"]},
  gideaPark: {displayName: "Gidea Park", lines: ["elizabeth"]},
  gillinghamKent: {displayName: "Gillingham (Kent)", lines: ["thameslink"]},
  gipsyHill: {displayName: "Gipsy Hill", lines: ["thameslink"]},
  gloucesterRoad: {displayName: "Gloucester Road", lines: ["district", "piccadilly", "circle"]},
  glynde: {displayName: "Glynde", lines: ["thameslink"]},
  godstone: {displayName: "Godstone", lines: ["thameslink"]},
  goldersGreen: {displayName: "Golders Green", lines: ["northern"]},
  goldhawkRoad: {displayName: "Goldhawk Road", lines: ["hammersmithAndCity", "circle"]},
  goodgeStreet: {displayName: "Goodge Street", lines: ["northern"]},
  goodmayes: {displayName: "Goodmayes", lines: ["elizabeth"]},
  gordonHill: {displayName: "Gordon Hill", lines: ["thameslink"]},
  goringBySea: {displayName: "Goring-by-Sea", lines: ["thameslink"]},
  gospelOak: {displayName: "Gospel Oak", lines: ["mildmay", "suffragette"]},
  grangeHill: {displayName: "Grange Hill", lines: ["central"]},
  grangePark: {displayName: "Grange Park", lines: ["thameslink"]},
  gravelHill: {displayName: "Gravel Hill", lines: ["trams"]},
  gravesend: {displayName: "Gravesend", lines: ["thameslink"]},
  greatPortlandStreet: {displayName: "Great Portland Street", lines: ["metropolitan", "circle", "hammersmithAndCity"]},
  greenPark: {displayName: "Green Park", lines: ["piccadilly", "victoria", "jubilee"]},
  greenford: {displayName: "Greenford", lines: ["central"]},
  greenhithe: {displayName: "Greenhithe", lines: ["thameslink"]},
  greenwich: {displayName: "Greenwich", lines: ["dlr", "thameslink"]},
  greenwichPeninsula: {displayName: "IFS Cloud Greenwich Peninsula", lines: ["cableCar"]},
  guildford: {displayName: "Guildford", lines: ["thameslink"]},
  gunnersbury: {displayName: "Gunnersbury", lines: ["mildmay", "district"]},
  hackbridge: {displayName: "Hackbridge", lines: ["thameslink"]},
  hackneyCentral: {displayName: "Hackney Central", lines: ["mildmay"]},
  hackneyDowns: {displayName: "Hackney Downs", lines: ["weaver"]},
  hackneyWick: {displayName: "Hackney Wick", lines: ["mildmay"]},
  hadleyWood: {displayName: "Hadley Wood", lines: ["thameslink"]},
  haggerston: {displayName: "Haggerston", lines: ["windrush"]},
  hainault: {displayName: "Hainault", lines: ["central"]},
  hamStreet: {displayName: "Ham Street", lines: ["thameslink"]},
  hamble: {displayName: "Hamble", lines: ["thameslink"]},
  hammersmith1: {displayName: "Hammersmith", lines: ["district", "piccadilly"]},
  hammersmith2: {displayName: "Hammersmith", lines: ["hammersmithAndCity", "circle"]},
  hampdenParkSussex: {displayName: "Hampden Park (Sussex)", lines: ["thameslink"]},
  hampstead: {displayName: "Hampstead", lines: ["northern"]},
  hampsteadHeath: {displayName: "Hampstead Heath", lines: ["mildmay"]},
  hangerLane: {displayName: "Hanger Lane", lines: ["central"]},
  hanwell: {displayName: "Hanwell", lines: ["elizabeth"]},
  harlesden: {displayName: "Harlesden", lines: ["bakerloo", "lioness"]},
  harlingtonBeds: {displayName: "Harlington (Beds)", lines: ["thameslink"]},
  haroldWood: {displayName: "Harold Wood", lines: ["elizabeth"]},
  harpenden: {displayName: "Harpenden", lines: ["thameslink"]},
  harringay: {displayName: "Harringay", lines: ["thameslink"]},
  harringayGreenLanes: {displayName: "Harringay Green Lanes", lines: ["suffragette"]},
  harringtonRoad: {displayName: "Harrington Road", lines: ["trams"]},
  harrowAndWealdstone: {displayName: "Harrow & Wealdstone", lines: ["bakerloo", "lioness", "thameslink"]},
  harrowOnTheHill: {displayName: "Harrow-on-the-Hill", lines: ["metropolitan"]},
  hassocks: {displayName: "Hassocks", lines: ["thameslink"]},
  hastings: {displayName: "Hastings", lines: ["thameslink"]},
  hatchEnd: {displayName: "Hatch End", lines: ["lioness"]},
  hatfieldHerts: {displayName: "Hatfield (Herts)", lines: ["thameslink"]},
  hattonCross: {displayName: "Hatton Cross", lines: ["piccadilly"]},
  havant: {displayName: "Havant", lines: ["thameslink"]},
  haydonsRoad: {displayName: "Haydons Road", lines: ["thameslink"]},
  hayesAndHarlington: {displayName: "Hayes & Harlington", lines: ["elizabeth"]},
  haywardsHeath: {displayName: "Haywards Heath", lines: ["thameslink"]},
  headstoneLane: {displayName: "Headstone Lane", lines: ["lioness"]},
  heathrowTerminalFive: {displayName: "Heathrow Terminal 5", lines: ["piccadilly", "elizabeth"]},
  heathrowTerminalFour: {displayName: "Heathrow Terminal 4", lines: ["piccadilly", "elizabeth"]},
  heathrowTerminalsTwoAndThree: {displayName: "Heathrow Terminals 2 & 3", lines: ["piccadilly", "elizabeth"]},
  hemelHempstead: {displayName: "Hemel Hempstead", lines: ["thameslink"]},
  hendon: {displayName: "Hendon", lines: ["thameslink"]},
  hendonCentral: {displayName: "Hendon Central", lines: ["northern"]},
  herneHill: {displayName: "Herne Hill", lines: ["thameslink"]},
  heronQuays: {displayName: "Heron Quays", lines: ["dlr"]},
  hertfordNorth: {displayName: "Hertford North", lines: ["thameslink"]},
  hever: {displayName: "Hever", lines: ["thameslink"]},
  highBarnet: {displayName: "High Barnet", lines: ["northern"]},
  highStreetKensington: {displayName: "High Street Kensington", lines: ["district", "circle"]},
  highamKent: {displayName: "Higham (Kent)", lines: ["thameslink"]},
  highamsPark: {displayName: "Highams Park", lines: ["weaver"]},
  highburyAndIslington: {displayName: "Highbury & Islington", lines: ["victoria", "mildmay", "windrush", "thameslink"]},
  highgate: {displayName: "Highgate", lines: ["northern"]},
  hillingdon: {displayName: "Hillingdon", lines: ["metropolitan", "piccadilly"]},
  hilsea: {displayName: "Hilsea", lines: ["thameslink"]},
  hitchin: {displayName: "Hitchin", lines: ["thameslink"]},
  holborn: {displayName: "Holborn", lines: ["central", "piccadilly"]},
  hollandPark: {displayName: "Holland Park", lines: ["central"]},
  hollowayRoad: {displayName: "Holloway Road", lines: ["piccadilly"]},
  holmwood: {displayName: "Holmwood", lines: ["thameslink"]},
  homerton: {displayName: "Homerton", lines: ["mildmay"]},
  honorOakPark: {displayName: "Honor Oak Park", lines: ["windrush", "thameslink"]},
  horley: {displayName: "Horley", lines: ["thameslink"]},
  hornchurch: {displayName: "Hornchurch", lines: ["district"]},
  hornsey: {displayName: "Hornsey", lines: ["thameslink"]},
  horsham: {displayName: "Horsham", lines: ["thameslink"]},
  horsley: {displayName: "Horsley", lines: ["thameslink"]},
  hounslowCentral: {displayName: "Hounslow Central", lines: ["piccadilly"]},
  hounslowEast: {displayName: "Hounslow East", lines: ["piccadilly"]},
  hounslowWest: {displayName: "Hounslow West", lines: ["piccadilly"]},
  hove: {displayName: "Hove", lines: ["thameslink"]},
  hoxton: {displayName: "Hoxton", lines: ["windrush"]},
  huntingdon: {displayName: "Huntingdon", lines: ["thameslink"]},
  hurstGreen: {displayName: "Hurst Green", lines: ["thameslink"]},
  hydeParkCorner: {displayName: "Hyde Park Corner", lines: ["piccadilly"]},
  ickenham: {displayName: "Ickenham", lines: ["metropolitan", "piccadilly"]},
  ifield: {displayName: "Ifield", lines: ["thameslink"]},
  ilford: {displayName: "Ilford", lines: ["elizabeth"]},
  imperialWharf: {displayName: "Imperial Wharf", lines: ["mildmay", "thameslink"]},
  islandGardens: {displayName: "Island Gardens", lines: ["dlr"]},
  iver: {displayName: "Iver", lines: ["elizabeth"]},
  kenley: {displayName: "Kenley", lines: ["thameslink"]},
  kennington: {displayName: "Kennington", lines: ["northern"]},
  kensalGreen: {displayName: "Kensal Green", lines: ["bakerloo", "lioness"]},
  kensalRise: {displayName: "Kensal Rise", lines: ["mildmay"]},
  kensingtonOlympia: {displayName: "Kensington (Olympia)", lines: ["district", "mildmay", "thameslink"]},
  kentishTown: {displayName: "Kentish Town", lines: ["northern", "thameslink"]},
  kentishTownWest: {displayName: "Kentish Town West", lines: ["mildmay"]},
  kenton: {displayName: "Kenton", lines: ["bakerloo", "lioness"]},
  kewGardens: {displayName: "Kew Gardens", lines: ["district", "mildmay"]},
  kilburn: {displayName: "Kilburn", lines: ["jubilee"]},
  kilburnHighRoad: {displayName: "Kilburn High Road", lines: ["lioness"]},
  kilburnPark: {displayName: "Kilburn Park", lines: ["bakerloo"]},
  kingGeorgeV: {displayName: "King George V", lines: ["dlr"]},
  kingHenrysDrive: {displayName: "King Henry's Drive", lines: ["trams"]},
  kingsCrossStPancras: {displayName: "King's Cross St Pancras", lines: ["metropolitan", "northern", "piccadilly", "circle", "victoria", "hammersmithAndCity"]},
  kingsLynn: {displayName: "Kings Lynn", lines: ["thameslink"]},
  kingsbury: {displayName: "Kingsbury", lines: ["jubilee"]},
  kingswood: {displayName: "Kingswood", lines: ["thameslink"]},
  knebworth: {displayName: "Knebworth", lines: ["thameslink"]},
  knightsbridge: {displayName: "Knightsbridge", lines: ["piccadilly"]},
  ladbrokeGrove: {displayName: "Ladbroke Grove", lines: ["hammersmithAndCity", "circle"]},
  lambethNorth: {displayName: "Lambeth North", lines: ["bakerloo"]},
  lancasterGate: {displayName: "Lancaster Gate", lines: ["central"]},
  lancing: {displayName: "Lancing", lines: ["thameslink"]},
  langdonPark: {displayName: "Langdon Park", lines: ["dlr"]},
  langley: {displayName: "Langley", lines: ["elizabeth"]},
  latimerRoad: {displayName: "Latimer Road", lines: ["hammersmithAndCity", "circle"]},
  leagrave: {displayName: "Leagrave", lines: ["thameslink"]},
  leatherhead: {displayName: "Leatherhead", lines: ["thameslink"]},
  lebanonRoad: {displayName: "Lebanon Road", lines: ["trams"]},
  leicesterSquare: {displayName: "Leicester Square", lines: ["piccadilly", "northern"]},
  leighKent: {displayName: "Leigh (Kent)", lines: ["thameslink"]},
  leightonBuzzard: {displayName: "Leighton Buzzard", lines: ["thameslink"]},
  letchworthGardenCity: {displayName: "Letchworth Garden City", lines: ["thameslink"]},
  lewes: {displayName: "Lewes", lines: ["thameslink"]},
  lewisham: {displayName: "Lewisham", lines: ["dlr"]},
  leyton: {displayName: "Leyton", lines: ["central"]},
  leytonMidlandRoad: {displayName: "Leyton Midland Road", lines: ["suffragette"]},
  leytonstone: {displayName: "Leytonstone", lines: ["central"]},
  leytonstoneHighRoad: {displayName: "Leytostone High Road", lines: ["suffragette"]},
  limehouse: {displayName: "Limehouse", lines: ["dlr"]},
  lingfield: {displayName: "Lingfield", lines: ["thameslink"]},
  littlehampton: {displayName: "Littlehampton", lines: ["thameslink"]},
  littlehaven: {displayName: "Littlehaven", lines: ["thameslink"]},
  littleport: {displayName: "Littleport", lines: ["thameslink"]},
  liverpoolStreet: {displayName: "Liverpool Street", lines: ["metropolitan", "central", "circle", "hammersmithAndCity", "weaver", "elizabeth"]},
  lloydPark: {displayName: "Lloyd Park", lines: ["trams"]},
  londonBlackfriars: {displayName: "London Blackfriars", lines: ["thameslink"]},
  londonBridge: {displayName: "London Bridge", lines: ["northern", "jubilee", "thameslink"]},
  londonCityAirport: {displayName: "London City Airport", lines: ["dlr"]},
  londonFields: {displayName: "London Fields", lines: ["weaver"]},
  londonKingsCross: {displayName: "London Kings Cross", lines: ["thameslink"]},
  londonRoadBrighton: {displayName: "London Road (Brighton)", lines: ["thameslink"]},
  londonRoadGuildford: {displayName: "London Road (Guildford)", lines: ["thameslink"]},
  londonStPancrasInternational: {displayName: "London St Pancras International", lines: ["thameslink"]},
  loughboroughJunction: {displayName: "Loughborough Junction", lines: ["thameslink"]},
  loughton: {displayName: "Loughton", lines: ["central"]},
  luton: {displayName: "Luton", lines: ["thameslink"]},
  lutonAirportParkway: {displayName: "Luton Airport Parkway", lines: ["thameslink"]},
  maidaVale: {displayName: "Maida Vale", lines: ["bakerloo"]},
  maidenhead: {displayName: "maidenhead", lines: ["elizabeth"]},
  manorHouse: {displayName: "Manor House", lines: ["piccadilly"]},
  manorPark: {displayName: "Manor Park", lines: ["elizabeth"]},
  mansionHouse: {displayName: "Mansion House", lines: ["district", "circle"]},
  marbleArch: {displayName: "Marble Arch", lines: ["central"]},
  maryland: {displayName: "Maryland", lines: ["elizabeth"]},
  marylebone: {displayName: "Marylebone", lines: ["bakerloo"]},
  mazeHill: {displayName: "Maze Hill", lines: ["thameslink"]},
  meldreth: {displayName: "Meldreth", lines: ["thameslink"]},
  merstham: {displayName: "Merstham", lines: ["thameslink"]},
  mertonPark: {displayName: "Merton Park", lines: ["trams"]},
  mileEnd: {displayName: "Mile End", lines: ["district", "hammersmithAndCity", "central"]},
  millHillBroadway: {displayName: "Mill Hill Broadway", lines: ["thameslink"]},
  millHillEast: {displayName: "Mill Hill East", lines: ["northern"]},
  miltonKeynesCentral: {displayName: "Milton Keynes Central", lines: ["thameslink"]},
  mitcham: {displayName: "Mitcham", lines: ["trams"]},
  mitchamEastfields: {displayName: "Mitcham Eastfields", lines: ["thameslink"]},
  mitchamJunction: {displayName: "Mitcham Junction", lines: ["trams", "thameslink"]},
  monument: {displayName: "Monument", lines: ["district", "circle"]},
  moorPark: {displayName: "Moor Park", lines: ["metropolitan"]},
  moorgate: {displayName: "Moorgate", lines: ["metropolitan", "northern", "circle", "hammersmithAndCity", "thameslink"]},
  morden: {displayName: "Morden", lines: ["northern"]},
  mordenRoad: {displayName: "Morden Road", lines: ["trams"]},
  mordenSouth: {displayName: "Morden South", lines: ["thameslink"]},
  morningtonCrescent: {displayName: "Mornington Crescent", lines: ["northern"]},
  moulsecoomb: {displayName: "Moulsecoomb", lines: ["thameslink"]},
  mudchute: {displayName: "Mudchute", lines: ["dlr"]},
  neasden: {displayName: "Neasden", lines: ["jubilee"]},
  netley: {displayName: "Netley", lines: ["thameslink"]},
  newAddington: {displayName: "New Addington", lines: ["trams"]},
  newBarnet: {displayName: "New Barnet", lines: ["thameslink"]},
  newCross: {displayName: "New Cross", lines: ["windrush"]},
  newCrossGate: {displayName: "New Cross Gate", lines: ["windrush", "thameslink"]},
  newSouthgate: {displayName: "New Southgate", lines: ["thameslink"]},
  newburyPark: {displayName: "Newbury Park", lines: ["central"]},
  newhavenHarbour: {displayName: "Newhaven Harbour", lines: ["thameslink"]},
  newhavenTown: {displayName: "Newhaven Town", lines: ["thameslink"]},
  nineElms: {displayName: "Nine Elms", lines: ["northern"]},
  norbury: {displayName: "Norbury", lines: ["thameslink"]},
  normansBay: {displayName: "Normans Bay", lines: ["thameslink"]},
  northActon: {displayName: "North Acton", lines: ["central"]},
  northDulwich: {displayName: "North Dulwich", lines: ["thameslink"]},
  northEaling: {displayName: "North Ealing", lines: ["piccadilly"]},
  northHarrow: {displayName: "North Harrow", lines: ["metropolitan"]},
  northWembley: {displayName: "North Wembley", lines: ["bakerloo", "lioness"]},
  northfields: {displayName: "Northfields", lines: ["piccadilly"]},
  northfleet: {displayName: "Northfleet", lines: ["thameslink"]},
  northolt: {displayName: "Northolt", lines: ["central"]},
  northwickPark: {displayName: "Northwick Park", lines: ["metropolitan"]},
  northwood: {displayName: "Northwood", lines: ["metropolitan"]},
  northwoodHills: {displayName: "Northwood Hills", lines: ["metropolitan"]},
  norwoodJunction: {displayName: "Norwood Junction", lines: ["windrush", "thameslink"]},
  nottingHillGate: {displayName: "Notting Hill Gate", lines: ["district", "central", "circle"]},
  nunhead: {displayName: "Nunhead", lines: ["thameslink"]},
  nutbourne: {displayName: "Nutbourne", lines: ["thameslink"]},
  nutfield: {displayName: "Nutfield", lines: ["thameslink"]},
  oakleighPark: {displayName: "Oakleigh Park", lines: ["thameslink"]},
  oakwood: {displayName: "Oakwood", lines: ["piccadilly"]},
  ockley: {displayName: "Ockley", lines: ["thameslink"]},
  oldStreet: {displayName: "Old Street", lines: ["northern", "thameslink"]},
  ore: {displayName: "Ore", lines: ["thameslink"]},
  orpington: {displayName: "Orpington", lines: ["thameslink"]},
  osterley: {displayName: "Osterley", lines: ["piccadilly"]},
  otford: {displayName: "Otford", lines: ["thameslink"]},
  oval: {displayName: "Oval", lines: ["northern"]},
  oxfordCircus: {displayName: "Oxford Circus", lines: ["central", "bakerloo", "victoria"]},
  oxted: {displayName: "Oxted", lines: ["thameslink"]},
  paddington: {displayName: "Paddington", lines: ["district", "circle", "bakerloo", "hammersmithAndCity", "elizabeth"]},
  palmersGreen: {displayName: "Palmers Green", lines: ["thameslink"]},
  parkRoyal: {displayName: "Park Royal", lines: ["piccadilly"]},
  parsonsGreen: {displayName: "Parsons Green", lines: ["district"]},
  peckhamRye: {displayName: "Peckham Rye", lines: ["windrush", "thameslink"]},
  pengeWest: {displayName: "Penge West", lines: ["windrush", "thameslink"]},
  penshurst: {displayName: "Penshurst", lines: ["thameslink"]},
  perivale: {displayName: "Perivale", lines: ["central"]},
  peterborough: {displayName: "Peterborough", lines: ["thameslink"]},
  pettsWood: {displayName: "Petts Wood", lines: ["thameslink"]},
  pevenseyAndWestham: {displayName: "Pevensey & Westham", lines: ["thameslink"]},
  pevenseyBay: {displayName: "Pevensey Bay", lines: ["thameslink"]},
  phippsBridge: {displayName: "Phipps Bridge", lines: ["trams"]},
  piccadillyCircus: {displayName: "Piccadilly Circus", lines: ["bakerloo", "piccadilly"]},
  pimlico: {displayName: "Pimlico", lines: ["victoria"]},
  pinner: {displayName: "Pinner", lines: ["metropolitan"]},
  plaistow: {displayName: "Plaistow", lines: ["district", "hammersmithAndCity"]},
  plumpton: {displayName: "Plumpton", lines: ["thameslink"]},
  plumstead: {displayName: "Plumstead", lines: ["thameslink"]},
  polegate: {displayName: "Polegate", lines: ["thameslink"]},
  pontoonDock: {displayName: "Pontoon Dock", lines: ["dlr"]},
  poplar: {displayName: "Poplar", lines: ["dlr"]},
  portchester: {displayName: "Portchester", lines: ["thameslink"]},
  portslade: {displayName: "Portslade", lines: ["thameslink"]},
  portsmouthAndSouthsea: {displayName: "Portsmouth & Southsea", lines: ["thameslink"]},
  portsmouthHarbour: {displayName: "Portsmouth Harbour", lines: ["thameslink"]},
  pottersBar: {displayName: "Potters Bar", lines: ["thameslink"]},
  prestonPark: {displayName: "Preston Park", lines: ["thameslink"]},
  prestonRoad: {displayName: "Preston Road", lines: ["metropolitan"]},
  princeRegent: {displayName: "Prince Regent", lines: ["dlr"]},
  puddingMillLane: {displayName: "Pudding Mill Lane", lines: ["elizabeth"]},
  pulborough: {displayName: "Pulborough", lines: ["thameslink"]},
  purley: {displayName: "Purley", lines: ["thameslink"]},
  purleyOaks: {displayName: "Purley Oaks", lines: ["thameslink"]},
  queensPark: {displayName: "Queen's Park", lines: ["bakerloo", "lioness"]},
  queensRoadPeckham: {displayName: "Queens Road Peckham", lines: ["windrush", "thameslink"]},
  queensbury: {displayName: "Queensbury", lines: ["jubilee"]},
  queensway: {displayName: "Queensway", lines: ["central"]},
  radlett: {displayName: "Radlett", lines: ["thameslink"]},
  rainhamKent: {displayName: "Rainham (Kent)", lines: ["thameslink"]},
  ravensbourne: {displayName: "Ravensbourne", lines: ["thameslink"]},
  ravenscourtPark: {displayName: "Ravenscourt Park", lines: ["district"]},
  raynersLane: {displayName: "Rayners Lane", lines: ["metropolitan", "piccadilly"]},
  reading: {displayName: "Reading", lines: ["elizabeth"]},
  rectoryRoad: {displayName: "Rectory Road", lines: ["weaver"]},
  redbridge: {displayName: "Redbridge", lines: ["central"]},
  redhill: {displayName: "Redhill", lines: ["thameslink"]},
  reedhamSurrey: {displayName: "Reedham (Surrey)", lines: ["thameslink"]},
  reevesCorner: {displayName: "Reeves Corner", lines: ["trams"]},
  regentsPark: {displayName: "Regents Park", lines: ["bakerloo"]},
  reigate: {displayName: "Reigate", lines: ["thameslink"]},
  richmond: {displayName: "Richmond", lines: ["district", "mildmay"]},
  rickmansworth: {displayName: "Rickmansworth", lines: ["metropolitan"]},
  riddlesdown: {displayName: "Riddlesdown", lines: ["thameslink"]},
  rochester: {displayName: "Rochester", lines: ["thameslink"]},
  rodingValley: {displayName: "Roding Valley", lines: ["central"]},
  romford: {displayName: "Romford", lines: ["liberty", "elizabeth"]},
  rotherhithe: {displayName: "Rotherhithe", lines: ["windrush"]},
  royalAlbert: {displayName: "Royal Albert", lines: ["dlr"]},
  royalDocks: {displayName: "IFS Cloud Royal Docks", lines: ["cableCar"]},
  royalOak: {displayName: "Royal Oak", lines: ["hammersmithAndCity", "circle"]},
  royalVictoria: {displayName: "Royal Victoria", lines: ["dlr"]},
  royston: {displayName: "Royston", lines: ["thameslink"]},
  ruislip: {displayName: "Ruislip", lines: ["metropolitan", "piccadilly"]},
  ruislipGardens: {displayName: "Ruislip Gardens", lines: ["central"]},
  ruislipManor: {displayName: "Ruislip Manor", lines: ["metropolitan", "piccadilly"]},
  russellSquare: {displayName: "Russell Square", lines: ["piccadilly"]},
  ryeSussex: {displayName: "Rye (Sussex)", lines: ["thameslink"]},
  salfordsSurrey: {displayName: "Salfords (Surrey)", lines: ["thameslink"]},
  sanderstead: {displayName: "Sanderstead", lines: ["thameslink"]},
  sandilands: {displayName: "Sandilands", lines: ["trams"]},
  sandy: {displayName: "Sandy", lines: ["thameslink"]},
  seafordSussex: {displayName: "Seaford (Sussex)", lines: ["thameslink"]},
  selhurst: {displayName: "Selhurst", lines: ["thameslink"]},
  sevenKings: {displayName: "Seven Kings", lines: ["elizabeth"]},
  sevenSisters: {displayName: "Seven Sisters", lines: ["victoria", "weaver"]},
  sevenoaks: {displayName: "Sevenoaks", lines: ["thameslink"]},
  shadwell: {displayName: "Shadwell", lines: ["windrush", "dlr"]},
  shenfield: {displayName: "Shenfield", lines: ["elizabeth"]},
  shepherdsBush: {displayName: "Shepherd's Bush", lines: ["central", "mildmay", "thameslink"]},
  shepherdsBushMarket: {displayName: "Shepherd's Bush Market", lines: ["hammersmithAndCity", "circle"]},
  shepreth: {displayName: "Shepreth", lines: ["thameslink"]},
  sholing: {displayName: "Sholing", lines: ["thameslink"]},
  shoreditchHighStreet: {displayName: "Shoreditch High Street", lines: ["windrush"]},
  shorehamBySea: {displayName: "Shoreham-by-Sea", lines: ["thameslink"]},
  shorehamKent: {displayName: "Shoreham (Kent)", lines: ["thameslink"]},
  shortlands: {displayName: "Shortlands", lines: ["thameslink"]},
  silverStreet: {displayName: "Silver Street", lines: ["weaver"]},
  sladeGreen: {displayName: "Slade Green", lines: ["thameslink"]},
  sloaneSquare: {displayName: "Sloane Square", lines: ["district", "circle"]},
  slough: {displayName: "Slough", lines: ["elizabeth"]},
  snaresbrook: {displayName: "Snaresbrook", lines: ["central"]},
  southActon: {displayName: "South Acton", lines: ["mildmay"]},
  southBermondsey: {displayName: "South Bermondsey", lines: ["thameslink"]},
  southCroydon: {displayName: "South Croydon", lines: ["thameslink"]},
  southEaling: {displayName: "South Ealing", lines: ["piccadilly"]},
  southHampstead: {displayName: "South Hampstead", lines: ["lioness"]},
  southHarrow: {displayName: "South Harrow", lines: ["piccadilly"]},
  southKensington: {displayName: "South Kensington", lines: ["district", "circle", "piccadilly"]},
  southKenton: {displayName: "South Kenton", lines: ["bakerloo", "lioness"]},
  southMerton: {displayName: "South Merton", lines: ["thameslink"]},
  southQuay: {displayName: "South Quay", lines: ["dlr"]},
  southRuislip: {displayName: "South Ruislip", lines: ["central"]},
  southTottenham: {displayName: "South Tottenham", lines: ["suffragette"]},
  southWimbledon: {displayName: "South Wimbledon", lines: ["northern"]},
  southWoodford: {displayName: "South Woodford", lines: ["central"]},
  southall: {displayName: "Southall", lines: ["elizabeth"]},
  southamptonAirportParkway: {displayName: "Southampton Airport Parkway", lines: ["thameslink"]},
  southamptonCentral: {displayName: "Southampton Central", lines: ["thameslink"]},
  southbourne: {displayName: "Southbourne", lines: ["thameslink"]},
  southbury: {displayName: "Southbury", lines: ["weaver"]},
  southease: {displayName: "Southease", lines: ["thameslink"]},
  southfields: {displayName: "Southfields", lines: ["district"]},
  southgate: {displayName: "Southgate", lines: ["piccadilly"]},
  southwark: {displayName: "Southwark", lines: ["jubilee"]},
  southwick: {displayName: "Southwick", lines: ["thameslink"]},
  stAlbansCity: {displayName: "St Albans City", lines: ["thameslink"]},
  stDenys: {displayName: "St Denys", lines: ["thameslink"]},
  stHelierSurrey: {displayName: "St Helier (Surrey)", lines: ["thameslink"]},
  stJamesPark: {displayName: "St James's Park", lines: ["district", "circle"]},
  stJamesStreet: {displayName: "St James Street", lines: ["weaver"]},
  stJohnsWood: {displayName: "St John's Wood", lines: ["jubilee"]},
  stLeonardsWarriorSquare: {displayName: "St Leonards Warrior Square", lines: ["thameslink"]},
  stMaryCray: {displayName: "St Mary Cray", lines: ["thameslink"]},
  stNeots: {displayName: "St Neots", lines: ["thameslink"]},
  stPauls: {displayName: "St Paul's", lines: ["central"]},
  stamfordBrook: {displayName: "Stamford Brook", lines: ["district"]},
  stamfordHill: {displayName: "Stamford Hill", lines: ["weaver"]},
  stanmore: {displayName: "Stanmore", lines: ["jubilee"]},
  starLane: {displayName: "Star Lane", lines: ["dlr"]},
  stepneyGreen: {displayName: "Stepney Green", lines: ["district", "hammersmithAndCity"]},
  stevenage: {displayName: "Stevenage", lines: ["thameslink"]},
  stockwell: {displayName: "Stockwell", lines: ["victoria", "northern"]},
  stokeNewington: {displayName: "Stoke Newington", lines: ["weaver"]},
  stoneCrossing: {displayName: "Stone Crossing", lines: ["thameslink"]},
  stonebridgePark: {displayName: "Stonebridge Park", lines: ["bakerloo", "lioness"]},
  stratford: {displayName: "Stratford", lines: ["central", "jubilee", "mildmay", "elizabeth", "dlr"]},
  stratfordHighStreet: {displayName: "Stratford High Street", lines: ["dlr"]},
  stratfordInternational: {displayName: "Stratford International", lines: ["dlr"]},
  streathamCommon: {displayName: "Streatham Common", lines: ["thameslink"]},
  streathamGreaterLondon: {displayName: "Streatham (Greater London)", lines: ["thameslink"]},
  streathamHill: {displayName: "Streatham Hill", lines: ["thameslink"]},
  stroodKent: {displayName: "Strood (Kent)", lines: ["thameslink"]},
  sudburyHill: {displayName: "Sudbury Hill", lines: ["piccadilly"]},
  sudburyTown: {displayName: "Sudbury Town", lines: ["piccadilly"]},
  surreyQuays: {displayName: "Surrey Quays", lines: ["windrush"]},
  suttonCommon: {displayName: "Sutton Common", lines: ["thameslink"]},
  suttonLondon: {displayName: "Sutton (London)", lines: ["thameslink"]},
  swanley: {displayName: "Swanley", lines: ["thameslink"]},
  swanscombe: {displayName: "Swanscombe", lines: ["thameslink"]},
  swanwick: {displayName: "Swanwick", lines: ["thameslink"]},
  swissCottage: {displayName: "Swiss Cottage", lines: ["jubilee"]},
  sydenham: {displayName: "Sydenham", lines: ["windrush"]},
  sydenhamLondon: {displayName: "Sydenham (London)", lines: ["thameslink"]},
  tadworth: {displayName: "Tadworth", lines: ["thameslink"]},
  taplow: {displayName: "Taplow", lines: ["elizabeth"]},
  tattenhamCorner: {displayName: "Tattenham Corner", lines: ["thameslink"]},
  temple: {displayName: "Temple", lines: ["district", "circle"]},
  theobaldsGrove: {displayName: "Theobalds Grove", lines: ["weaver"]},
  therapiaLane: {displayName: "Therapia Lane", lines: ["trams"]},
  theydonBois: {displayName: "Theydon Bois", lines: ["central"]},
  thorntonHeath: {displayName: "Thornton Heath", lines: ["thameslink"]},
  threeBridges: {displayName: "Three Bridges", lines: ["thameslink"]},
  threeOaks: {displayName: "Three Oaks", lines: ["thameslink"]},
  tooting: {displayName: "Tooting", lines: ["thameslink"]},
  tootingBec: {displayName: "Tooting Bec", lines: ["northern"]},
  tootingBroadway: {displayName: "Tooting Broadway", lines: ["northern"]},
  tottenhamCourtRoad: {displayName: "Tottenham Court Road", lines: ["northern", "central", "elizabeth"]},
  tottenhamHale: {displayName: "Tottenham Hale", lines: ["victoria"]},
  totteridgeAndWhetstone: {displayName: "Totteridge & Whetstone", lines: ["northern"]},
  towerGateway: {displayName: "Tower Gateway", lines: ["dlr"]},
  towerHill: {displayName: "Tower Hill", lines: ["district", "circle"]},
  tring: {displayName: "Tring", lines: ["thameslink"]},
  tufnellPark: {displayName: "Tufnell Park", lines: ["northern"]},
  tulseHill: {displayName: "Tulse Hill", lines: ["thameslink"]},
  turkeyStreet: {displayName: "Turkey Street", lines: ["weaver"]},
  turnhamGreen: {displayName: "Turnham Green", lines: ["district", "piccadilly"]},
  turnpikeLane: {displayName: "Turnpike Lane", lines: ["piccadilly"]},
  twyford: {displayName: "Twyford", lines: ["elizabeth"]},
  uckfield: {displayName: "Uckfield", lines: ["thameslink"]},
  upminster: {displayName: "Upminster", lines: ["district", "liberty"]},
  upminsterBridge: {displayName: "Upminster Bridge", lines: ["district"]},
  upney: {displayName: "Upney", lines: ["district"]},
  upperHolloway: {displayName: "Upper Holloway", lines: ["suffragette"]},
  upperWarlingham: {displayName: "Upper Warlingham", lines: ["thameslink"]},
  uptonPark: {displayName: "Upton Park", lines: ["district"]},
  uxbridge: {displayName: "Uxbridge", lines: ["metropolitan", "piccadilly"]},
  vauxhall: {displayName: "Vauxhall", lines: ["victoria"]},
  victoria: {displayName: "Victoria", lines: ["victoria", "district", "circle"]},
  waddon: {displayName: "Waddon", lines: ["thameslink"]},
  waddonMarsh: {displayName: "Waddon Marsh", lines: ["trams"]},
  wallington: {displayName: "Wallington", lines: ["thameslink"]},
  walthamstowCentral: {displayName: "Walthamstow Central", lines: ["victoria", "weaver"]},
  walthamstowQueensRoad: {displayName: "Walthamstow Queen's Road", lines: ["suffragette"]},
  wandlePark: {displayName: "Wandle Park", lines: ["trams"]},
  wandsworthCommon: {displayName: "Wandsworth Common", lines: ["thameslink"]},
  wandsworthRoad: {displayName: "Wandsworth Road", lines: ["windrush"]},
  wanstead: {displayName: "Wanstead", lines: ["central"]},
  wansteadPark: {displayName: "Wanstead Park", lines: ["suffragette"]},
  wapping: {displayName: "Wapping", lines: ["windrush"]},
  warblington: {displayName: "Warblington", lines: ["thameslink"]},
  warnham: {displayName: "Warnham", lines: ["thameslink"]},
  warrenStreet: {displayName: "Warren Street", lines: ["northern", "victoria"]},
  warwickAvenue: {displayName: "Warwick Avenue", lines: ["bakerloo"]},
  waterbeach: {displayName: "Waterbeach", lines: ["thameslink"]},
  waterloo: {displayName: "Waterloo", lines: ["waterlooAndCity", "bakerloo", "northern", "jubilee"]},
  watford: {displayName: "Watford", lines: ["metropolitan"]},
  watfordHighStreet: {displayName: "Watford High Street", lines: ["lioness"]},
  watfordJunction: {displayName: "Watford Junction", lines: ["lioness", "thameslink"]},
  watlington: {displayName: "Watlington", lines: ["thameslink"]},
  wattonAtStone: {displayName: "Watton-at-Stone", lines: ["thameslink"]},
  welhamGreen: {displayName: "Welham Green", lines: ["thameslink"]},
  wellesleyRoad: {displayName: "Wellesley Road", lines: ["trams"]},
  welwynGardenCity: {displayName: "Welwyn Garden City", lines: ["thameslink"]},
  welwynNorth: {displayName: "Welwyn North", lines: ["thameslink"]},
  wembleyCentral: {displayName: "Wembley Central", lines: ["bakerloo", "lioness", "thameslink"]},
  wembleyPark: {displayName: "Wembley Park", lines: ["metropolitan", "jubilee"]},
  westActon: {displayName: "West Acton", lines: ["central"]},
  westBrompton: {displayName: "West Brompton", lines: ["thameslink"]},
  westCroydon: {displayName: "West Croydon", lines: ["windrush", "trams"]},
  westDrayton: {displayName: "West Drayton", lines: ["elizabeth"]},
  westEaling: {displayName: "West Ealing", lines: ["elizabeth"]},
  westFichley: {displayName: "West Finchley", lines: ["northern"]},
  westHam: {displayName: "West Ham", lines: ["district", "hammersmithAndCity", "jubilee", "dlr"]},
  westHampstead: {displayName: "West Hampstead", lines: ["jubilee", "mildmay"]},
  westHampsteadThameslink: {displayName: "West Hampstead Thameslink", lines: ["thameslink"]},
  westHarrow: {displayName: "West Harrow", lines: ["metropolitan"]},
  westIndiaQuay: {displayName: "West India Quay", lines: ["dlr"]},
  westKensington: {displayName: "West Kensington", lines: ["district"]},
  westNorwood: {displayName: "West Norwood", lines: ["thameslink"]},
  westRuislip: {displayName: "West Ruislip", lines: ["central"]},
  westSilvertown: {displayName: "West Silvertown", lines: ["dlr"]},
  westSutton: {displayName: "West Sutton", lines: ["thameslink"]},
  westWorthing: {displayName: "West Worthing", lines: ["thameslink"]},
  westbournePark: {displayName: "Westbourne Park", lines: ["hammersmithAndCity", "circle"]},
  westbrompton: {displayName: "West Brompton", lines: ["district", "mildmay"]},
  westcombePark: {displayName: "Westcombe Park", lines: ["thameslink"]},
  westferry: {displayName: "Westferry", lines: ["dlr"]},
  westminster: {displayName: "Westminster", lines: ["district", "circle", "jubilee"]},
  whiteCity: {displayName: "White City", lines: ["central"]},
  whiteHartLane: {displayName: "White Hart Lane", lines: ["weaver"]},
  whitechapel: {displayName: "Whitechapel", lines: ["district", "hammersmithAndCity", "windrush", "elizabeth"]},
  whyteleafe: {displayName: "Whyteleafe", lines: ["thameslink"]},
  whyteleafeSouth: {displayName: "Whyteleafe South", lines: ["thameslink"]},
  willesdenGreen: {displayName: "Willesden Green", lines: ["jubilee"]},
  willesdenJunction: {displayName: "Willesden Junction", lines: ["bakerloo", "lioness", "mildmay"]},
  wimbledon: {displayName: "Wimbledon", lines: ["district", "trams", "thameslink"]},
  wimbledonChase: {displayName: "Wimbledon Chase", lines: ["thameslink"]},
  wimbledonPark: {displayName: "Wimbledon Park", lines: ["district"]},
  winchelsea: {displayName: "Winchelsea", lines: ["thameslink"]},
  winchmoreHill: {displayName: "Winchmore Hill", lines: ["thameslink"]},
  wivelsfield: {displayName: "Wivelsfield", lines: ["thameslink"]},
  woldingham: {displayName: "Woldingham", lines: ["thameslink"]},
  woodGreen: {displayName: "Wood Green", lines: ["piccadilly"]},
  woodStreet: {displayName: "Wood Street", lines: ["weaver"]},
  woodford: {displayName: "Woodford", lines: ["central"]},
  woodgrangePark: {displayName: "Woodgrange Park", lines: ["suffragette"]},
  woodmansterne: {displayName: "Woodmansterne", lines: ["thameslink"]},
  woodside: {displayName: "Woodside", lines: ["trams"]},
  woodsidePark: {displayName: "Woodside Park", lines: ["northern"]},
  woolston: {displayName: "Woolston", lines: ["thameslink"]},
  woolwich: {displayName: "Woolwich", lines: ["elizabeth"]},
  woolwichArsenal: {displayName: "Woolwich Arsenal", lines: ["dlr", "thameslink"]},
  worthing: {displayName: "Worthing", lines: ["thameslink"]},
} as const satisfies Record<string, Station>;

export type StationId = keyof typeof Stations;
export const stationIds = Object.keys(Stations) as StationId[];
